// gen_pipeline.mjs — generate a depth-D PIPELINE benchmark in three forms:
//   1. pipe_dD.kjs            — Koru source (emit via koruc --lang=js)
//   2. pipe_dD_dynamic.mjs    — same pipeline via Node EventEmitter (per-hop dynamic dispatch)
//   3. pipe_dD_flat.mjs       — same pipeline as plain direct function calls (no dispatch)
//
// Shape (LINEAR in depth, not exponential):
//   source fires `! item` M times (a loop of M).
//   each item handler passes through D pass-through stages: stage1 -> ... -> stageD,
//   each a SINGLE call (not a loop).
//   innermost stage calls plain inc() -> counter++.
//   report prints counter.
// Result: counter === M. Total dispatch hops = M*(D+1) — linear in D.
//
// NOTE on void effects: Koru rejects a single no-payload branch (PARSE003), so a
// truly payload-less effect (`! item` with no type) is not legal. chain.kjs's
// working pattern is `! v u64` — a u64 payload that is fired then ignored
// (`! v _ |>`). We match that exactly: every effect carries a throwaway u64.
//
// Usage: node gen_pipeline.mjs <D>

import { writeFileSync } from "node:fs";

const D = parseInt(process.argv[2] || "4");
if (!Number.isInteger(D) || D < 1) {
  console.error(`bad depth: ${process.argv[2]}`);
  process.exit(1);
}

// ----------------------------------------------------------------------------
// 1. Koru source
// ----------------------------------------------------------------------------
function genKoru(D) {
  let s = "";
  s += `// pipe_d${D}.kjs — depth-${D} pass-through pipeline. Generated by gen_pipeline.mjs.\n`;
  s += `const M = parseInt(process.argv[2] || "1000000");\n`;
  s += `let counter = 0;\n\n`;

  // source: loops M, fires `item` once per element.
  s += `~pub event source { m: u64 }\n`;
  s += `! item u64\n`;
  s += `~proc source|js { for (let i = 0; i < m; i++) item(i); }\n\n`;

  // D pass-through stages, each fires its `v` effect exactly once.
  for (let k = 1; k <= D; k++) {
    s += `~pub event stage${k} {}\n`;
    s += `! v u64\n`;
    s += `~proc stage${k}|js { v(0); }\n\n`;
  }

  // inc: plain event, bumps counter.
  s += `~pub event inc {}\n`;
  s += `~proc inc|js { counter++; }\n\n`;

  // report: plain event, prints counter.
  s += `~pub event report {}\n`;
  s += `~proc report|js { console.log("counter = " + counter); }\n\n`;

  // The flow: source ! item _ |> stage1() ! v _ |> stage2() ... stageD() ! v _ |> inc()
  s += `~source(m: M)\n`;
  s += `! item _ |>\n`;
  let indent = "    ";
  for (let k = 1; k <= D; k++) {
    s += `${indent}stage${k}()\n`;
    if (k < D) {
      s += `${indent}! v _ |>\n`;
      indent += "    ";
    } else {
      // innermost stage: fire v then call inc()
      s += `${indent}! v _ |> inc()\n`;
    }
  }
  s += `\n~report()\n`;
  return s;
}

// ----------------------------------------------------------------------------
// 2. Dynamic: Node EventEmitter, per-hop dynamic dispatch. FAIR, not a strawman.
// ----------------------------------------------------------------------------
function genDynamic(D) {
  let s = "";
  s += `// pipe_d${D}_dynamic.mjs — depth-${D} pipeline via Node EventEmitter.\n`;
  s += `// Per-hop dynamic dispatch (string-keyed listener registry) at every stage.\n`;
  s += `import { EventEmitter } from "node:events";\n\n`;
  s += `const M = parseInt(process.argv[2] || "1000000");\n`;
  s += `let counter = 0;\n\n`;

  // inc emitter
  s += `const inc = new EventEmitter();\n`;
  s += `inc.on("fire", () => { counter++; });\n\n`;

  // stage emitters: stageK "v" listener triggers stage(K+1) "fire";
  // last stage's "v" triggers inc.
  for (let k = 1; k <= D; k++) {
    s += `const stage${k} = new EventEmitter();\n`;
    if (k < D) {
      s += `stage${k}.on("v", () => { stage${k + 1}.emit("fire"); });\n`;
    } else {
      s += `stage${k}.on("v", () => { inc.emit("fire"); });\n`;
    }
    // "fire" on stageK fires its "v" once (single pass-through call).
    s += `stage${k}.on("fire", () => { stage${k}.emit("v"); });\n\n`;
  }

  // source emitter: "item" listener triggers stage1; "run" loops M firing "item".
  s += `const source = new EventEmitter();\n`;
  s += `source.on("item", () => { stage1.emit("fire"); });\n`;
  s += `source.on("run", (m) => { for (let i = 0; i < m; i++) source.emit("item", i); });\n\n`;

  // report emitter
  s += `const report = new EventEmitter();\n`;
  s += `report.on("fire", () => { console.log("counter = " + counter); });\n\n`;

  s += `source.emit("run", M);\n`;
  s += `report.emit("fire");\n`;
  return s;
}

// ----------------------------------------------------------------------------
// 3. Flat: plain direct function calls, no dispatch. The lower bound.
// ----------------------------------------------------------------------------
function genFlat(D) {
  let s = "";
  s += `// pipe_d${D}_flat.mjs — depth-${D} pipeline as plain direct function calls.\n`;
  s += `const M = parseInt(process.argv[2] || "1000000");\n`;
  s += `let counter = 0;\n\n`;
  s += `function inc() { counter++; }\n`;
  // stageD calls inc; stageK calls stage(K+1).
  for (let k = D; k >= 1; k--) {
    if (k === D) {
      s += `function stage${k}() { inc(); }\n`;
    } else {
      s += `function stage${k}() { stage${k + 1}(); }\n`;
    }
  }
  s += `function source(m) { for (let i = 0; i < m; i++) stage1(); }\n`;
  s += `function report() { console.log("counter = " + counter); }\n\n`;
  s += `source(M);\n`;
  s += `report();\n`;
  return s;
}

writeFileSync(`pipe_d${D}.kjs`, genKoru(D));
writeFileSync(`pipe_d${D}_dynamic.mjs`, genDynamic(D));
writeFileSync(`pipe_d${D}_flat.mjs`, genFlat(D));
console.log(`generated pipe_d${D}.kjs, pipe_d${D}_dynamic.mjs, pipe_d${D}_flat.mjs`);
