// Koru Backend (Pass 2) for: greet_with_branches.kz
// This file IS the compiler backend - it generates final code at compile-time

// Generated by Koru AST Serializer
// This file contains the complete program AST as Zig data structures

// AST Type Definitions

const SourceFile = struct {
    items: []const Item,
};

const Item = union(enum) {
    zig_line: ZigLine,
    event_decl: EventDecl,
    proc_decl: ProcDecl,
    flow: Flow,
    import_decl: ImportDecl,
    subflow_impl: SubflowImpl,
    label_decl: LabelDecl,
    module_decl: ModuleDecl,
};

const ZigLine = struct {
    content: []const u8,
};

const ModuleDecl = struct {
    logical_name: []const u8,
    canonical_path: []const u8,
    items: []const Item,
    is_system: bool,
};

const EventDecl = struct {
    path: []const []const u8,
    input: Shape,
    branches: []const Branch,
    is_public: bool,
    is_implicit_flow: bool,
    annotations: []const []const u8,
};

const Shape = struct {
    fields: []const Field,
};

const Field = struct {
    name: []const u8,
    type: []const u8,
    is_flow_ast: bool,
    is_source: bool,
    is_file: bool,
    is_embed_file: bool,
    phantom: ?[]const u8,
    expression: ?*const void = null,
    expression_str: ?[]const u8 = null,
    owns_expression: bool = false,
};

const Branch = struct {
    name: []const u8,
    payload: Shape,
    is_deferred: bool,
};

const ProcDecl = struct {
    path: []const []const u8,
    body: []const u8,  // The Zig code body
    inline_flows: []const Flow = &.{},
    annotations: []const []const u8 = &.{},
};

const Flow = struct {
    invocation: Invocation,
    continuations: []const Continuation,
    pre_label: ?[]const u8,
    post_label: ?[]const u8,
    super_shape: ?*const Shape = null,
};

const Invocation = struct {
    path: []const []const u8,
    args: []const Arg,
};

const Arg = struct {
    name: []const u8,
    value: []const u8,
    ast_value: ?*const FlowAST,
};

const FlowAST = struct {
    flows: []const Flow,
};

const Continuation = struct {
    branch: []const u8,
    binding: ?[]const u8,
    pipeline: []const Step,
    indent: usize,
    nested: []const Continuation,
};

const Step = union(enum) {
    invocation: Invocation,
    label_apply: []const u8,
    label_with_invocation: struct {
        label: []const u8,
        invocation: Invocation,
    },
    terminal: void,
    deref: struct {
        target: []const u8,
        args: ?[]const Arg,
    },
    branch_constructor: BranchConstructor,
};

const BranchConstructor = struct {
    branch_name: []const u8,
    fields: []const Field,
    has_expressions: bool = false,
};

const ImportDecl = struct {
    path: []const u8,
    name: ?[]const u8,
};

const SubflowImpl = struct {
    event_path: []const []const u8,
    body: SubflowBody,
};

const SubflowBody = union(enum) {
    flow: Flow,
    immediate: BranchConstructor,
};

const LabelDecl = struct {
    name: []const u8,
    continuations: []const Continuation,
};

// ProgramAST is the type used by compiler events to reference the AST
const ProgramAST = *const SourceFile;

pub const PROGRAM_AST = SourceFile{
    .items = &[_]Item{
        .{ .zig_line = .{ .content = "// Simplified Koru Compiler Library" } },
        .{ .zig_line = .{ .content = "// A working implementation that can actually be injected and used" } },
        .{ .zig_line = .{ .content = "// ============================================================" } },
        .{ .zig_line = .{ .content = "// ARCHITECTURAL CONSTRAINT: NO INLINE FLOWS IN COMPILER PROCS" } },
        .{ .zig_line = .{ .content = "// ============================================================" } },
        .{ .zig_line = .{ .content = "// Compiler procs (compiler.*) MUST be pure Zig code." } },
        .{ .zig_line = .{ .content = "// They CANNOT use inline flows (~event syntax) because:" } },
        .{ .zig_line = .{ .content = "// " } },
        .{ .zig_line = .{ .content = "// 1. They run at Zig compile-time (no Koru runtime exists)" } },
        .{ .zig_line = .{ .content = "// 2. The compiler that processes flows doesn't exist yet" } },
        .{ .zig_line = .{ .content = "// 3. This is the bootstrap - it must be minimal and simple" } },
        .{ .zig_line = .{ .content = "//" } },
        .{ .zig_line = .{ .content = "// This is NOT a limitation but a FEATURE - it keeps the" } },
        .{ .zig_line = .{ .content = "// metacircular foundation small, simple, and trustworthy." } },
        .{ .zig_line = .{ .content = "// " } },
        .{ .zig_line = .{ .content = "// User code can use ALL Koru features. Only the compiler" } },
        .{ .zig_line = .{ .content = "// itself is restricted to pure Zig, which is perfect for" } },
        .{ .zig_line = .{ .content = "// the string manipulation and AST walking it needs to do." } },
        .{ .zig_line = .{ .content = "// ============================================================" } },
        .{ .zig_line = .{ .content = "// The default compiler coordinator" } },
        .{ .event_decl = EventDecl{
            .path = &[_][]const u8{"compiler", "coordinate", "default"},
            .input = Shape{ .fields = &[_]Field{
                Field{ .name = "ast", .type = "ProgramAST", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
            } },
            .branches = &[_]Branch{
                Branch{
                    .name = "coordinated",
                    .payload = Shape{ .fields = &[_]Field{
                        Field{ .name = "ast", .type = "ProgramAST", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                        Field{ .name = "code", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                        Field{ .name = "metrics", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                    } },
                    .is_deferred = false,
                },
            },
            .is_public = true,
            .is_implicit_flow = false,
            .annotations = &[_][]const u8{
            },
        } },
        .{ .zig_line = .{ .content = "// Zig code emission event - the final step of compilation!" } },
        .{ .event_decl = EventDecl{
            .path = &[_][]const u8{"compiler", "emit", "zig"},
            .input = Shape{ .fields = &[_]Field{
                Field{ .name = "ast", .type = "ProgramAST", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
            } },
            .branches = &[_]Branch{
                Branch{
                    .name = "emitted",
                    .payload = Shape{ .fields = &[_]Field{
                        Field{ .name = "code", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                    } },
                    .is_deferred = false,
                },
            },
            .is_public = true,
            .is_implicit_flow = false,
            .annotations = &[_][]const u8{
            },
        } },
        .{ .zig_line = .{ .content = "// Implementation of Zig code emission - this IS ComptimeEmitter as a Koru proc!" } },
        .{ .proc_decl = ProcDecl{
            .path = &[_][]const u8{"compiler", "emit", "zig"},
            .body = 
                \\
                \\    const MAX_SIZE = 64 * 1024; // 64KB buffer
                \\    var buffer: [MAX_SIZE]u8 = undefined;
                \\    var pos: usize = 0;
                \\    
                \\    // Helper function for writing strings
                \\    const writeStr = struct {
                \\        fn call(buf: *[MAX_SIZE]u8, p: usize, str: []const u8) usize {
                \\            if (p + str.len >= MAX_SIZE) return p;
                \\            @memcpy(buf[p..p + str.len], str);
                \\            return p + str.len;
                \\        }
                \\    }.call;
                \\    
                \\    // Helper function for equality comparison
                \\    const eql = struct {
                \\        fn call(a: []const u8, b: []const u8) bool {
                \\            if (a.len != b.len) return false;
                \\            for (a, 0..) |char, i| {
                \\                if (char != b[i]) return false;
                \\            }
                \\            return true;
                \\        }
                \\    }.call;
                \\    
                \\    
                \\    // Generate header
                \\    pos = writeStr(&buffer, pos, "// Generated by Koru compiler.emit.zig event - METACIRCULAR!\n");
                \\    pos = writeStr(&buffer, pos, "\n");
                \\    
                \\    // Check if there's a user-defined main function or any flows/events
                \\    var has_user_main = false;
                \\    var has_flows = false;
                \\    var has_events = false;
                \\    
                \\    for (e.ast.items) |item| {
                \\        switch (item) {
                \\            .zig_line => |line| {
                \\                // Simple check: if line starts with "pub fn main"
                \\                if (line.content.len >= 11 and eql(line.content[0..11], "pub fn main")) {
                \\                    has_user_main = true;
                \\                }
                \\            },
                \\            .flow => {
                \\                has_flows = true;
                \\            },
                \\            .event_decl => |event| {
                \\                // Skip compiler events
                \\                if (event.path.len == 0 or !eql(event.path[0], "compiler")) {
                \\                    has_events = true;
                \\                }
                \\            },
                \\            else => {},
                \\        }
                \\    }
                \\    
                \\    // If user defined main and no Koru features, just output as-is
                \\    if (has_user_main and !has_flows and !has_events) {
                \\        // Just output zig_lines directly without module struct
                \\        for (e.ast.items) |item| {
                \\            switch (item) {
                \\                .zig_line => |line| {
                \\                    pos = writeStr(&buffer, pos, line.content);
                \\                    pos = writeStr(&buffer, pos, "\n");
                \\                },
                \\                else => {},
                \\            }
                \\        }
                \\        // Return early - no need for further processing
                \\        const final_code = buffer[0..pos];
                \\        return .{ .emitted = .{ .code = final_code } };
                \\    }
                \\    
                \\    // First, generate imported module structs from ModuleDecl items
                \\    for (e.ast.items) |item| {
                \\        switch (item) {
                \\            .module_decl => |module| {
                \\                pos = writeStr(&buffer, pos, "pub const ");
                \\                pos = writeStr(&buffer, pos, module.logical_name);
                \\                pos = writeStr(&buffer, pos, " = struct {\n");
                \\                
                \\                // Process all items in the module
                \\                for (module.items) |mod_item| {
                \\                    switch (mod_item) {
                \\                        .zig_line => |line| {
                \\                            pos = writeStr(&buffer, pos, "    ");
                \\                            pos = writeStr(&buffer, pos, line.content);
                \\                            pos = writeStr(&buffer, pos, "\n");
                \\                        },
                \\                        .event_decl => |event| {
                \\                            // Skip compiler events (they're only for compile-time use)
                \\                            // TODO: Use event.is_compiler_internal flag once available
                \\                            if (event.path.len > 0 and eql(event.path[0], "compiler")) {
                \\                                continue;
                \\                            }
                \\                            
                \\                            // Generate event struct
                \\                            pos = writeStr(&buffer, pos, "    pub const ");
                \\                            pos = writeStr(&buffer, pos, event.path[event.path.len - 1]);
                \\                            pos = writeStr(&buffer, pos, " = struct {\n");
                \\                            
                \\                            // Input struct
                \\                            pos = writeStr(&buffer, pos, "        pub const Input = struct {\n");
                \\                            for (event.input.fields) |field| {
                \\                                pos = writeStr(&buffer, pos, "            ");
                \\                                pos = writeStr(&buffer, pos, field.name);
                \\                                pos = writeStr(&buffer, pos, ": ");
                \\                                if (field.is_file or field.is_embed_file) {
                \\                                    pos = writeStr(&buffer, pos, "[]const u8");
                \\                                } else {
                \\                                    pos = writeStr(&buffer, pos, field.type);
                \\                                }
                \\                                pos = writeStr(&buffer, pos, ",\n");
                \\                            }
                \\                            pos = writeStr(&buffer, pos, "        };\n");
                \\                            
                \\                            // Output union
                \\                            pos = writeStr(&buffer, pos, "        pub const Output = union(enum) {\n");
                \\                            for (event.branches) |branch| {
                \\                                pos = writeStr(&buffer, pos, "            ");
                \\                                pos = writeStr(&buffer, pos, branch.name);
                \\                                pos = writeStr(&buffer, pos, ": struct {\n");
                \\                                for (branch.payload.fields) |field| {
                \\                                    pos = writeStr(&buffer, pos, "                ");
                \\                                    pos = writeStr(&buffer, pos, field.name);
                \\                                    pos = writeStr(&buffer, pos, ": ");
                \\                                    pos = writeStr(&buffer, pos, field.type);
                \\                                    pos = writeStr(&buffer, pos, ",\n");
                \\                                }
                \\                                pos = writeStr(&buffer, pos, "            },\n");
                \\                            }
                \\                            pos = writeStr(&buffer, pos, "        };\n");
                \\                            
                \\                            // Handler function
                \\                            pos = writeStr(&buffer, pos, "        pub fn handler(e: Input) Output {\n");
                \\                            
                \\                            // Find implementation in the same module
                \\                            var found_impl = false;
                \\                            for (module.items) |impl_item| {
                \\                                switch (impl_item) {
                \\                                    .proc_decl => |proc| {
                \\                                        if (proc.path.len == event.path.len) {
                \\                                            var matches = true;
                \\                                            for (proc.path, 0..) |seg, j| {
                \\                                                if (!eql(seg, event.path[j])) {
                \\                                                    matches = false;
                \\                                                    break;
                \\                                                }
                \\                                            }
                \\                                            if (matches) {
                \\                                                pos = writeStr(&buffer, pos, "            _ = &e;\n");
                \\                                                pos = writeStr(&buffer, pos, proc.body);
                \\                                                pos = writeStr(&buffer, pos, "\n");
                \\                                                found_impl = true;
                \\                                                break;
                \\                                            }
                \\                                        }
                \\                                    },
                \\                                    else => {},
                \\                                }
                \\                            }
                \\                            
                \\                            if (!found_impl) {
                \\                                if (event.branches.len > 0) {
                \\                                    pos = writeStr(&buffer, pos, "            return .{ .");
                \\                                    pos = writeStr(&buffer, pos, event.branches[0].name);
                \\                                    pos = writeStr(&buffer, pos, " = .{} };\n");
                \\                                } else {
                \\                                    pos = writeStr(&buffer, pos, "            return undefined;\n");
                \\                                }
                \\                            }
                \\                            
                \\                            pos = writeStr(&buffer, pos, "        }\n");
                \\                            pos = writeStr(&buffer, pos, "    };\n");
                \\                        },
                \\                        else => {},
                \\                    }
                \\                }
                \\                
                \\                // Close the module struct
                \\                pos = writeStr(&buffer, pos, "};\n\n");
                \\            },
                \\            else => {},
                \\        }
                \\    }
                \\    
                \\    // Now generate the main module struct
                \\    pos = writeStr(&buffer, pos, "pub const main_module = struct {\n");
                \\    
                \\    // First pass: Collect zig_lines (imports) - inside the module struct!
                \\    for (e.ast.items) |item| {
                \\        switch (item) {
                \\            .module_decl => continue,  // Skip module declarations
                \\            .zig_line => |line| {
                \\                pos = writeStr(&buffer, pos, "    ");
                \\                pos = writeStr(&buffer, pos, line.content);
                \\                pos = writeStr(&buffer, pos, "\n");
                \\            },
                \\            else => {},
                \\        }
                \\    }
                \\    
                \\    // Second pass: Generate events (only local ones, not imported)
                \\    for (e.ast.items) |item| {
                \\        switch (item) {
                \\            .module_decl => continue,  // Skip module declarations
                \\            .event_decl => |event| {
                \\                // Skip compiler events
                \\                if (event.path.len > 0 and eql(event.path[0], "compiler")) {
                \\                    continue;
                \\                }
                \\                
                \\                // Write the event with proper indentation (we're inside main_module)
                \\                pos = writeStr(&buffer, pos, "    pub const ");
                \\                pos = writeStr(&buffer, pos, event.path[event.path.len - 1]);
                \\                pos = writeStr(&buffer, pos, " = struct {\n");
                \\                
                \\                // Input struct
                \\                pos = writeStr(&buffer, pos, "        pub const Input = struct {\n");
                \\                for (event.input.fields) |field| {
                \\                    pos = writeStr(&buffer, pos, "            ");
                \\                    pos = writeStr(&buffer, pos, field.name);
                \\                    pos = writeStr(&buffer, pos, ": ");
                \\                    if (field.is_file or field.is_embed_file) {
                \\                        pos = writeStr(&buffer, pos, "[]const u8");
                \\                    } else {
                \\                        pos = writeStr(&buffer, pos, field.type);
                \\                    }
                \\                    pos = writeStr(&buffer, pos, ",\n");
                \\                }
                \\                pos = writeStr(&buffer, pos, "        };\n");
                \\                
                \\                // Output union
                \\                pos = writeStr(&buffer, pos, "        pub const Output = union(enum) {\n");
                \\                for (event.branches) |branch| {
                \\                    pos = writeStr(&buffer, pos, "            ");
                \\                    pos = writeStr(&buffer, pos, branch.name);
                \\                    pos = writeStr(&buffer, pos, ": struct {\n");
                \\                    for (branch.payload.fields) |field| {
                \\                        pos = writeStr(&buffer, pos, "                ");
                \\                        pos = writeStr(&buffer, pos, field.name);
                \\                        pos = writeStr(&buffer, pos, ": ");
                \\                        pos = writeStr(&buffer, pos, field.type);
                \\                        pos = writeStr(&buffer, pos, ",\n");
                \\                    }
                \\                    pos = writeStr(&buffer, pos, "            },\n");
                \\                }
                \\                pos = writeStr(&buffer, pos, "        };\n");
                \\                
                \\                // Handler function
                \\                pos = writeStr(&buffer, pos, "        pub fn handler(e: Input) Output {\n");
                \\                
                \\                // Find implementation
                \\                var found_impl = false;
                \\                for (e.ast.items) |impl_item| {
                \\                    switch (impl_item) {
                \\                        .proc_decl => |proc| {
                \\                            if (proc.path.len == event.path.len) {
                \\                                var matches = true;
                \\                                for (proc.path, 0..) |seg, j| {
                \\                                    if (!eql(seg, event.path[j])) {
                \\                                        matches = false;
                \\                                        break;
                \\                                    }
                \\                                }
                \\                                if (matches) {
                \\                                    pos = writeStr(&buffer, pos, "            _ = &e;\n");
                \\                                    pos = writeStr(&buffer, pos, proc.body);
                \\                                    pos = writeStr(&buffer, pos, "\n");
                \\                                    found_impl = true;
                \\                                    break;
                \\                                }
                \\                            }
                \\                        },
                \\                        .subflow_impl => |subflow| {
                \\                            if (subflow.event_path.len == event.path.len) {
                \\                                var matches = true;
                \\                                for (subflow.event_path, 0..) |seg, j| {
                \\                                    if (!eql(seg, event.path[j])) {
                \\                                        matches = false;
                \\                                        break;
                \\                                    }
                \\                                }
                \\                                if (matches) {
                \\                                    switch (subflow.body) {
                \\                                        .immediate => |bc| {
                \\                                            pos = writeStr(&buffer, pos, "            return .{ .");
                \\                                            pos = writeStr(&buffer, pos, bc.branch_name);
                \\                                            pos = writeStr(&buffer, pos, " = .{");
                \\                                            for (bc.fields, 0..) |field, k| {
                \\                                                if (k > 0) pos = writeStr(&buffer, pos, ", ");
                \\                                                pos = writeStr(&buffer, pos, " .");
                \\                                                pos = writeStr(&buffer, pos, field.name);
                \\                                                pos = writeStr(&buffer, pos, " = ");
                \\                                                pos = writeStr(&buffer, pos, field.type);
                \\                                            }
                \\                                            pos = writeStr(&buffer, pos, " } };\n");
                \\                                        },
                \\                                        .flow => {
                \\                                            pos = writeStr(&buffer, pos, "            // Flow subflow\n");
                \\                                            pos = writeStr(&buffer, pos, "            return undefined;\n");
                \\                                        },
                \\                                    }
                \\                                    found_impl = true;
                \\                                    break;
                \\                                }
                \\                            }
                \\                        },
                \\                        else => {},
                \\                    }
                \\                }
                \\                
                \\                if (!found_impl) {
                \\                    if (event.branches.len > 0) {
                \\                        pos = writeStr(&buffer, pos, "            return .{ .");
                \\                        pos = writeStr(&buffer, pos, event.branches[0].name);
                \\                        pos = writeStr(&buffer, pos, " = .{} };\n");
                \\                    } else {
                \\                        pos = writeStr(&buffer, pos, "            return undefined;\n");
                \\                    }
                \\                }
                \\                
                \\                pos = writeStr(&buffer, pos, "        }\n");
                \\                
                \\                // Close the event struct
                \\                pos = writeStr(&buffer, pos, "    };\n");
                \\            },
                \\            else => {},
                \\        }
                \\    }
                \\    
                \\    // Generate flows as functions inside main_module
                \\    var flow_counter: usize = 0;
                \\    for (e.ast.items) |item| {
                \\        switch (item) {
                \\            .flow => |flow| {
                \\                pos = writeStr(&buffer, pos, "    pub fn flow");
                \\                // Simple number writing
                \\                if (flow_counter == 0) {
                \\                    pos = writeStr(&buffer, pos, "0");
                \\                } else if (flow_counter == 1) {
                \\                    pos = writeStr(&buffer, pos, "1");
                \\                } else if (flow_counter == 2) {
                \\                    pos = writeStr(&buffer, pos, "2");
                \\                } else if (flow_counter == 3) {
                \\                    pos = writeStr(&buffer, pos, "3");
                \\                } else if (flow_counter == 4) {
                \\                    pos = writeStr(&buffer, pos, "4");
                \\                } else {
                \\                    pos = writeStr(&buffer, pos, "N");
                \\                }
                \\                pos = writeStr(&buffer, pos, "() void {\n");
                \\                
                \\                // Generate the flow body
                \\                pos = writeStr(&buffer, pos, "        const result = ");
                \\                
                \\                // Check if this event is in a module or main
                \\                var event_module: ?[]const u8 = null;
                \\                
                \\                // First check modules
                \\                for (e.ast.items) |evt_item| {
                \\                    switch (evt_item) {
                \\                        .module_decl => |module| {
                \\                            for (module.items) |mod_item| {
                \\                                switch (mod_item) {
                \\                                    .event_decl => |event| {
                \\                                        if (event.path.len == flow.invocation.path.len) {
                \\                                            var matches = true;
                \\                                            for (event.path, 0..) |seg, j| {
                \\                                                if (!eql(seg, flow.invocation.path[j])) {
                \\                                                    matches = false;
                \\                                                    break;
                \\                                                }
                \\                                            }
                \\                                            if (matches) {
                \\                                                event_module = module.logical_name;
                \\                                                break;
                \\                                            }
                \\                                        }
                \\                                    },
                \\                                    else => {},
                \\                                }
                \\                            }
                \\                            if (event_module != null) break;
                \\                        },
                \\                        else => {},
                \\                    }
                \\                }
                \\                
                \\                // Use module prefix if imported, otherwise local
                \\                if (event_module) |mod| {
                \\                    pos = writeStr(&buffer, pos, mod);
                \\                    pos = writeStr(&buffer, pos, ".");
                \\                    pos = writeStr(&buffer, pos, flow.invocation.path[flow.invocation.path.len - 1]);
                \\                } else {
                \\                    pos = writeStr(&buffer, pos, flow.invocation.path[flow.invocation.path.len - 1]);
                \\                }
                \\                pos = writeStr(&buffer, pos, ".handler(.{");
                \\                
                \\                for (flow.invocation.args, 0..) |arg, i| {
                \\                    if (i > 0) pos = writeStr(&buffer, pos, ", ");
                \\                    pos = writeStr(&buffer, pos, " .");
                \\                    pos = writeStr(&buffer, pos, arg.name);
                \\                    pos = writeStr(&buffer, pos, " = ");
                \\                    pos = writeStr(&buffer, pos, arg.value);
                \\                }
                \\                pos = writeStr(&buffer, pos, " });\n");
                \\                
                \\                // Handle the result (simplified for now)
                \\                pos = writeStr(&buffer, pos, "        switch (result) {\n");
                \\                
                \\                // Find the event to get branch names (check both modules and main)
                \\                var found_event = false;
                \\                for (e.ast.items) |evt_item| {
                \\                    switch (evt_item) {
                \\                        .module_decl => |module| {
                \\                            for (module.items) |mod_item| {
                \\                                switch (mod_item) {
                \\                                    .event_decl => |event| {
                \\                                        if (event.path.len == flow.invocation.path.len) {
                \\                                            var matches = true;
                \\                                            for (event.path, 0..) |seg, j| {
                \\                                                if (!eql(seg, flow.invocation.path[j])) {
                \\                                                    matches = false;
                \\                                                    break;
                \\                                                }
                \\                                            }
                \\                                            if (matches) {
                \\                                                for (event.branches) |branch| {
                \\                                                    pos = writeStr(&buffer, pos, "            .");
                \\                                                    pos = writeStr(&buffer, pos, branch.name);
                \\                                                    pos = writeStr(&buffer, pos, " => |v| {\n");
                \\                                                    pos = writeStr(&buffer, pos, "                _ = v; // Terminal\n");
                \\                                                    pos = writeStr(&buffer, pos, "            },\n");
                \\                                                }
                \\                                                found_event = true;
                \\                                                break;
                \\                                            }
                \\                                        }
                \\                                    },
                \\                                    else => {},
                \\                                }
                \\                            }
                \\                            if (found_event) break;
                \\                        },
                \\                        .event_decl => |event| {
                \\                            if (event.path.len == flow.invocation.path.len) {
                \\                                var matches = true;
                \\                                for (event.path, 0..) |seg, j| {
                \\                                    if (!eql(seg, flow.invocation.path[j])) {
                \\                                        matches = false;
                \\                                        break;
                \\                                    }
                \\                                }
                \\                                if (matches) {
                \\                                    for (event.branches) |branch| {
                \\                                        pos = writeStr(&buffer, pos, "            .");
                \\                                        pos = writeStr(&buffer, pos, branch.name);
                \\                                        pos = writeStr(&buffer, pos, " => |v| {\n");
                \\                                        pos = writeStr(&buffer, pos, "                _ = v; // Terminal\n");
                \\                                        pos = writeStr(&buffer, pos, "            },\n");
                \\                                    }
                \\                                    found_event = true;
                \\                                    break;
                \\                                }
                \\                            }
                \\                        },
                \\                        else => {},
                \\                    }
                \\                    if (found_event) break;
                \\                }
                \\                
                \\                pos = writeStr(&buffer, pos, "        }\n");
                \\                pos = writeStr(&buffer, pos, "    }\n\n");
                \\                
                \\                flow_counter += 1;
                \\            },
                \\            else => {},
                \\        }
                \\    }
                \\    
                \\    // Close the main_module struct
                \\    pos = writeStr(&buffer, pos, "};\n\n");
                \\    
                \\    // Generate minimal main function that calls flows from main_module
                \\    pos = writeStr(&buffer, pos, "pub fn main() void {\n");
                \\    
                \\    var flow_count: usize = 0;
                \\    for (e.ast.items) |item| {
                \\        switch (item) {
                \\            .flow => {
                \\                pos = writeStr(&buffer, pos, "    main_module.flow");
                \\                if (flow_count == 0) {
                \\                    pos = writeStr(&buffer, pos, "0");
                \\                } else if (flow_count == 1) {
                \\                    pos = writeStr(&buffer, pos, "1");
                \\                } else if (flow_count == 2) {
                \\                    pos = writeStr(&buffer, pos, "2");
                \\                } else if (flow_count == 3) {
                \\                    pos = writeStr(&buffer, pos, "3");
                \\                } else if (flow_count == 4) {
                \\                    pos = writeStr(&buffer, pos, "4");
                \\                } else {
                \\                    pos = writeStr(&buffer, pos, "N");
                \\                }
                \\                pos = writeStr(&buffer, pos, "();\n");
                \\                flow_count += 1;
                \\            },
                \\            else => {},
                \\        }
                \\    }
                \\    
                \\    pos = writeStr(&buffer, pos, "}\n");
                \\    
                \\    // Return the emitted code!
                \\    const final_code = buffer[0..pos];
                \\    return .{ .emitted = .{ .code = final_code } };
                ,
            .inline_flows = &[_]Flow{
            },
            .annotations = &[_][]const u8{
            },
        } },
        .{ .zig_line = .{ .content = "// Updated coordinator that calls emission!" } },
        .{ .subflow_impl = SubflowImpl{
            .event_path = &[_][]const u8{"compiler", "coordinate", "default"},
            .body = .{ .flow = Flow{
                .invocation = Invocation{
                    .path = &[_][]const u8{"compiler", "emit", "zig"},
                    .args = &[_]Arg{
                        Arg{ .name = "ast", .value = "e.ast", .ast_value = null },
                    },
                },
                .continuations = &[_]Continuation{
                    Continuation{
                        .branch = "emitted",
                        .binding = "em",
                        .pipeline = &[_]Step{
                            .{ .branch_constructor = BranchConstructor{
                                .branch_name = "coordinated",
                                .fields = &[_]Field{
                                    Field{ .name = "ast", .type = "e.ast", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                                    Field{ .name = "code", .type = "em.code", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                                    Field{ .name = "metrics", .type = "\"Metacircular compilation complete!\"", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                                },
                                .has_expressions = false,
                            } },
                        },
                        .indent = 4,
                        .nested = &[_]Continuation{
                        },
                    },
                },
                .pre_label = null,
                .post_label = null,
                .super_shape = null,
            } },
        } },
        .{ .module_decl = .{ .logical_name = "io", .canonical_path = "../../koru_std/io.kz", .items = &[_]Item{            
                                    .{ .zig_line = .{ .content = "// Koru Standard Library: I/O" } },            
                                    .{ .zig_line = .{ .content = "// Basic input/output operations for Koru programs" } },            
                                    .{ .zig_line = .{ .content = "//" } },            
                                    .{ .zig_line = .{ .content = "// Finally! After achieving consciousness (metacircular compilation)," } },            
                                    .{ .zig_line = .{ .content = "// we can now print \"Hello, World!\" " } },            
                                    .{ .zig_line = .{ .content = "const std = @import(\"std\");" } },            
                                    .{ .zig_line = .{ .content = "// Print text without newline" } },            
                                    .{ .event_decl = EventDecl{
                .path = &[_][]const u8{"io", "print"},
                .input = Shape{ .fields = &[_]Field{
                    Field{ .name = "text", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                } },
                .branches = &[_]Branch{
                    Branch{
                        .name = "printed",
                        .payload = Shape{ .fields = &[_]Field{
                        } },
                        .is_deferred = false,
                    },
                },
                .is_public = true,
                .is_implicit_flow = false,
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .proc_decl = ProcDecl{
                .path = &[_][]const u8{"io", "print"},
                .body = 
                    \\
                    \\    std.debug.print("{s}", .{e.text});
                    \\    return .{ .printed = .{} };
                    ,
                .inline_flows = &[_]Flow{
                },
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .zig_line = .{ .content = "// Print text with newline" } },            
                                    .{ .event_decl = EventDecl{
                .path = &[_][]const u8{"io", "println"},
                .input = Shape{ .fields = &[_]Field{
                    Field{ .name = "text", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                } },
                .branches = &[_]Branch{
                    Branch{
                        .name = "printed",
                        .payload = Shape{ .fields = &[_]Field{
                        } },
                        .is_deferred = false,
                    },
                    Branch{
                        .name = "failed",
                        .payload = Shape{ .fields = &[_]Field{
                            Field{ .name = "message", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                        } },
                        .is_deferred = false,
                    },
                },
                .is_public = true,
                .is_implicit_flow = false,
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .proc_decl = ProcDecl{
                .path = &[_][]const u8{"io", "println"},
                .body = 
                    \\
                    \\    std.debug.print("{s}\n", .{e.text});
                    \\    return .{ .printed = .{} };
                    ,
                .inline_flows = &[_]Flow{
                },
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .zig_line = .{ .content = "// Print formatted text" } },            
                                    .{ .zig_line = .{ .content = "// NOTE: printf with varargs would require runtime support - skipping for now" } },            
                                    .{ .zig_line = .{ .content = "// ~pub event io.printf { format: []const u8, args: anytype }" } },            
                                    .{ .zig_line = .{ .content = "// ~proc io.printf {" } },            
                                    .{ .zig_line = .{ .content = "//     std.debug.print(e.format, e.args);" } },            
                                    .{ .zig_line = .{ .content = "//     return .{ .printed = .{} };" } },            
                                    .{ .zig_line = .{ .content = "// }" } },            
                                    .{ .zig_line = .{ .content = "// Read line from stdin (for future interactive programs)" } },            
                                    .{ .event_decl = EventDecl{
                .path = &[_][]const u8{"io", "readln"},
                .input = Shape{ .fields = &[_]Field{
                } },
                .branches = &[_]Branch{
                    Branch{
                        .name = "line",
                        .payload = Shape{ .fields = &[_]Field{
                            Field{ .name = "text", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                        } },
                        .is_deferred = false,
                    },
                    Branch{
                        .name = "eof",
                        .payload = Shape{ .fields = &[_]Field{
                        } },
                        .is_deferred = false,
                    },
                    Branch{
                        .name = "failed",
                        .payload = Shape{ .fields = &[_]Field{
                            Field{ .name = "message", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                        } },
                        .is_deferred = false,
                    },
                },
                .is_public = true,
                .is_implicit_flow = false,
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .proc_decl = ProcDecl{
                .path = &[_][]const u8{"io", "readln"},
                .body = 
                    \\
                    \\    // TODO: Implement actual stdin reading
                    \\    // For now, return a placeholder
                    \\    return .{ .failed = .{ .message = "io.readln not yet implemented" } };
                    ,
                .inline_flows = &[_]Flow{
                },
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .zig_line = .{ .content = "// Debug print for development" } },            
                                    .{ .zig_line = .{ .content = "// NOTE: debug with anytype would require runtime support - skipping for now" } },            
                                    .{ .zig_line = .{ .content = "// ~pub event io.debug { label: []const u8, value: anytype }" } },            
                                    .{ .zig_line = .{ .content = "// ~proc io.debug {" } },            
                                    .{ .zig_line = .{ .content = "//     std.debug.print(\"[DEBUG {s}]: \", .{e.label});" } },            
                                    .{ .zig_line = .{ .content = "//     std.debug.print(\"{any}\\n\", .{e.value});" } },            
                                    .{ .zig_line = .{ .content = "//     return .{ .printed = .{} };" } },            
                                    .{ .zig_line = .{ .content = "// }" } },            
                                    .{ .zig_line = .{ .content = "// Print error to stderr" } },            
                                    .{ .event_decl = EventDecl{
                .path = &[_][]const u8{"io", "eprintln"},
                .input = Shape{ .fields = &[_]Field{
                    Field{ .name = "message", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                } },
                .branches = &[_]Branch{
                    Branch{
                        .name = "printed",
                        .payload = Shape{ .fields = &[_]Field{
                        } },
                        .is_deferred = false,
                    },
                },
                .is_public = true,
                .is_implicit_flow = false,
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .proc_decl = ProcDecl{
                .path = &[_][]const u8{"io", "eprintln"},
                .body = 
                    \\
                    \\    const stderr = std.io.getStdErr().writer();
                    \\    stderr.print("ERROR: {s}\n", .{e.message}) catch {
                    \\        // Fall back to debug print if stderr fails
                    \\        std.debug.print("ERROR: {s}\n", .{e.message});
                    \\    };
                    \\    return .{ .printed = .{} };
                    ,
                .inline_flows = &[_]Flow{
                },
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .zig_line = .{ .content = "// Success message with green color (if terminal supports it)" } },            
                                    .{ .event_decl = EventDecl{
                .path = &[_][]const u8{"io", "success"},
                .input = Shape{ .fields = &[_]Field{
                    Field{ .name = "message", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                } },
                .branches = &[_]Branch{
                    Branch{
                        .name = "printed",
                        .payload = Shape{ .fields = &[_]Field{
                        } },
                        .is_deferred = false,
                    },
                },
                .is_public = true,
                .is_implicit_flow = false,
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .proc_decl = ProcDecl{
                .path = &[_][]const u8{"io", "success"},
                .body = 
                    \\
                    \\    std.debug.print("✅ {s}\n", .{e.message});
                    \\    return .{ .printed = .{} };
                    ,
                .inline_flows = &[_]Flow{
                },
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .zig_line = .{ .content = "// Warning message" } },            
                                    .{ .event_decl = EventDecl{
                .path = &[_][]const u8{"io", "warn"},
                .input = Shape{ .fields = &[_]Field{
                    Field{ .name = "message", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                } },
                .branches = &[_]Branch{
                    Branch{
                        .name = "printed",
                        .payload = Shape{ .fields = &[_]Field{
                        } },
                        .is_deferred = false,
                    },
                },
                .is_public = true,
                .is_implicit_flow = false,
                .annotations = &[_][]const u8{
                },
            } },            
                                    .{ .proc_decl = ProcDecl{
                .path = &[_][]const u8{"io", "warn"},
                .body = 
                    \\
                    \\    std.debug.print("⚠️  {s}\n", .{e.message});
                    \\    return .{ .printed = .{} };
                    ,
                .inline_flows = &[_]Flow{
                },
                .annotations = &[_][]const u8{
                },
            } },        
                }, .is_system = false } },
        .{ .zig_line = .{ .content = "// Tour 01: Branches and Control Flow with I/O" } },
        .{ .zig_line = .{ .content = "// This demonstrates event branches and importing" } },
        .{ .zig_line = .{ .content = "// Import I/O for printing" } },
        .{ .zig_line = .{ .content = "// Import std for this module (each module needs its own)" } },
        .{ .zig_line = .{ .content = "const std = @import(\"std\");" } },
        .{ .zig_line = .{ .content = "// Event that processes a greeting request" } },
        .{ .event_decl = EventDecl{
            .path = &[_][]const u8{"process_greeting"},
            .input = Shape{ .fields = &[_]Field{
                Field{ .name = "name", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
            } },
            .branches = &[_]Branch{
                Branch{
                    .name = "friendly",
                    .payload = Shape{ .fields = &[_]Field{
                        Field{ .name = "msg", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                    } },
                    .is_deferred = false,
                },
                Branch{
                    .name = "formal",
                    .payload = Shape{ .fields = &[_]Field{
                        Field{ .name = "msg", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                    } },
                    .is_deferred = false,
                },
                Branch{
                    .name = "unknown",
                    .payload = Shape{ .fields = &[_]Field{
                    } },
                    .is_deferred = false,
                },
            },
            .is_public = false,
            .is_implicit_flow = false,
            .annotations = &[_][]const u8{
            },
        } },
        .{ .zig_line = .{ .content = "// Proc that decides how to greet based on the name" } },
        .{ .proc_decl = ProcDecl{
            .path = &[_][]const u8{"process_greeting"},
            .body = 
                \\
                \\    
                \\    // Check the name and return different branches
                \\    if (std.mem.eql(u8, e.name, "friend")) {
                \\        return .{ .friendly = .{ .msg = "Hey buddy! 👋" }};
                \\    } else if (std.mem.eql(u8, e.name, "boss")) {
                \\        return .{ .formal = .{ .msg = "Good day, sir/madam." }};
                \\    } else if (e.name.len == 0) {
                \\        return .{ .unknown = .{} };
                \\    } else {
                \\        // Generic friendly greeting for everyone else
                \\        return .{ .friendly = .{ .msg = "Hello there!" }};
                \\    }
                ,
            .inline_flows = &[_]Flow{
            },
            .annotations = &[_][]const u8{
            },
        } },
        .{ .zig_line = .{ .content = "// Main flow - demonstrate different branches" } },
        .{ .flow = Flow{
            .invocation = Invocation{
                .path = &[_][]const u8{"process_greeting"},
                .args = &[_]Arg{
                    Arg{ .name = "name", .value = "\"friend\"", .ast_value = null },
                },
            },
            .continuations = &[_]Continuation{
                Continuation{
                    .branch = "friendly",
                    .binding = "f",
                    .pipeline = &[_]Step{
                        .{ .invocation = Invocation{
                            .path = &[_][]const u8{"io", "println"},
                            .args = &[_]Arg{
                                Arg{ .name = "text", .value = "f.msg", .ast_value = null },
                            },
                        } },
                    },
                    .indent = 0,
                    .nested = &[_]Continuation{
                        Continuation{
                            .branch = "printed",
                            .binding = null,
                            .pipeline = &[_]Step{
                                .{ .terminal = {} },
                            },
                            .indent = 4,
                            .nested = &[_]Continuation{
                            },
                        },
                        Continuation{
                            .branch = "failed",
                            .binding = null,
                            .pipeline = &[_]Step{
                                .{ .terminal = {} },
                            },
                            .indent = 4,
                            .nested = &[_]Continuation{
                            },
                        },
                    },
                },
                Continuation{
                    .branch = "formal",
                    .binding = "f",
                    .pipeline = &[_]Step{
                        .{ .invocation = Invocation{
                            .path = &[_][]const u8{"io", "println"},
                            .args = &[_]Arg{
                                Arg{ .name = "text", .value = "f.msg", .ast_value = null },
                            },
                        } },
                    },
                    .indent = 0,
                    .nested = &[_]Continuation{
                        Continuation{
                            .branch = "printed",
                            .binding = null,
                            .pipeline = &[_]Step{
                                .{ .terminal = {} },
                            },
                            .indent = 4,
                            .nested = &[_]Continuation{
                            },
                        },
                        Continuation{
                            .branch = "failed",
                            .binding = null,
                            .pipeline = &[_]Step{
                                .{ .terminal = {} },
                            },
                            .indent = 4,
                            .nested = &[_]Continuation{
                            },
                        },
                    },
                },
                Continuation{
                    .branch = "unknown",
                    .binding = null,
                    .pipeline = &[_]Step{
                        .{ .invocation = Invocation{
                            .path = &[_][]const u8{"io", "println"},
                            .args = &[_]Arg{
                                Arg{ .name = "text", .value = "\"Who are you?\"", .ast_value = null },
                            },
                        } },
                    },
                    .indent = 0,
                    .nested = &[_]Continuation{
                        Continuation{
                            .branch = "printed",
                            .binding = null,
                            .pipeline = &[_]Step{
                                .{ .terminal = {} },
                            },
                            .indent = 4,
                            .nested = &[_]Continuation{
                            },
                        },
                        Continuation{
                            .branch = "failed",
                            .binding = null,
                            .pipeline = &[_]Step{
                                .{ .terminal = {} },
                            },
                            .indent = 4,
                            .nested = &[_]Continuation{
                            },
                        },
                    },
                },
            },
            .pre_label = null,
            .post_label = null,
            .super_shape = null,
        } },
        .{ .subflow_impl = SubflowImpl{
            .event_path = &[_][]const u8{"compiler", "coordinate"},
            .body = .{ .immediate = BranchConstructor{
                .branch_name = "coordinated",
                .fields = &[_]Field{
                    Field{ .name = "ast", .type = "e.ast", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                    Field{ .name = "metrics", .type = "\"Bootstrap compiler (library included)\"", .is_flow_ast = false, .is_source = false, .is_file = false, .is_embed_file = false, .phantom = null, .expression = null, .expression_str = null, .owns_expression = false },
                },
                .has_expressions = false,
            } },
        } },
    },
};


// Metacircular Code Generator

const compiler_emit_zig = struct {
    pub const Input = struct { ast: *const SourceFile };
    pub const Output = union(enum) { emitted: struct { code: []const u8 } };
    pub fn handler(e: Input) Output {

    const MAX_SIZE = 64 * 1024; // 64KB buffer
    var buffer: [MAX_SIZE]u8 = undefined;
    var pos: usize = 0;
    
    // Helper function for writing strings
    const writeStr = struct {
        fn call(buf: *[MAX_SIZE]u8, p: usize, str: []const u8) usize {
            if (p + str.len >= MAX_SIZE) return p;
            @memcpy(buf[p..p + str.len], str);
            return p + str.len;
        }
    }.call;
    
    // Helper function for equality comparison
    const eql = struct {
        fn call(a: []const u8, b: []const u8) bool {
            if (a.len != b.len) return false;
            for (a, 0..) |char, i| {
                if (char != b[i]) return false;
            }
            return true;
        }
    }.call;
    
    
    // Generate header
    pos = writeStr(&buffer, pos, "// Generated by Koru compiler.emit.zig event - METACIRCULAR!\n");
    pos = writeStr(&buffer, pos, "\n");
    
    // Check if there's a user-defined main function or any flows/events
    var has_user_main = false;
    var has_flows = false;
    var has_events = false;
    
    for (e.ast.items) |item| {
        switch (item) {
            .zig_line => |line| {
                // Simple check: if line starts with "pub fn main"
                if (line.content.len >= 11 and eql(line.content[0..11], "pub fn main")) {
                    has_user_main = true;
                }
            },
            .flow => {
                has_flows = true;
            },
            .event_decl => |event| {
                // Skip compiler events
                if (event.path.len == 0 or !eql(event.path[0], "compiler")) {
                    has_events = true;
                }
            },
            else => {},
        }
    }
    
    // If user defined main and no Koru features, just output as-is
    if (has_user_main and !has_flows and !has_events) {
        // Just output zig_lines directly without module struct
        for (e.ast.items) |item| {
            switch (item) {
                .zig_line => |line| {
                    pos = writeStr(&buffer, pos, line.content);
                    pos = writeStr(&buffer, pos, "\n");
                },
                else => {},
            }
        }
        // Return early - no need for further processing
        const final_code = buffer[0..pos];
        return .{ .emitted = .{ .code = final_code } };
    }
    
    // First, generate imported module structs from ModuleDecl items
    for (e.ast.items) |item| {
        switch (item) {
            .module_decl => |module| {
                pos = writeStr(&buffer, pos, "pub const ");
                pos = writeStr(&buffer, pos, module.logical_name);
                pos = writeStr(&buffer, pos, " = struct {\n");
                
                // Process all items in the module
                for (module.items) |mod_item| {
                    switch (mod_item) {
                        .zig_line => |line| {
                            pos = writeStr(&buffer, pos, "    ");
                            pos = writeStr(&buffer, pos, line.content);
                            pos = writeStr(&buffer, pos, "\n");
                        },
                        .event_decl => |event| {
                            // Skip compiler events (they're only for compile-time use)
                            // TODO: Use event.is_compiler_internal flag once available
                            if (event.path.len > 0 and eql(event.path[0], "compiler")) {
                                continue;
                            }
                            
                            // Generate event struct
                            pos = writeStr(&buffer, pos, "    pub const ");
                            pos = writeStr(&buffer, pos, event.path[event.path.len - 1]);
                            pos = writeStr(&buffer, pos, " = struct {\n");
                            
                            // Input struct
                            pos = writeStr(&buffer, pos, "        pub const Input = struct {\n");
                            for (event.input.fields) |field| {
                                pos = writeStr(&buffer, pos, "            ");
                                pos = writeStr(&buffer, pos, field.name);
                                pos = writeStr(&buffer, pos, ": ");
                                if (field.is_file or field.is_embed_file) {
                                    pos = writeStr(&buffer, pos, "[]const u8");
                                } else {
                                    pos = writeStr(&buffer, pos, field.type);
                                }
                                pos = writeStr(&buffer, pos, ",\n");
                            }
                            pos = writeStr(&buffer, pos, "        };\n");
                            
                            // Output union
                            pos = writeStr(&buffer, pos, "        pub const Output = union(enum) {\n");
                            for (event.branches) |branch| {
                                pos = writeStr(&buffer, pos, "            ");
                                pos = writeStr(&buffer, pos, branch.name);
                                pos = writeStr(&buffer, pos, ": struct {\n");
                                for (branch.payload.fields) |field| {
                                    pos = writeStr(&buffer, pos, "                ");
                                    pos = writeStr(&buffer, pos, field.name);
                                    pos = writeStr(&buffer, pos, ": ");
                                    pos = writeStr(&buffer, pos, field.type);
                                    pos = writeStr(&buffer, pos, ",\n");
                                }
                                pos = writeStr(&buffer, pos, "            },\n");
                            }
                            pos = writeStr(&buffer, pos, "        };\n");
                            
                            // Handler function
                            pos = writeStr(&buffer, pos, "        pub fn handler(e: Input) Output {\n");
                            
                            // Find implementation in the same module
                            var found_impl = false;
                            for (module.items) |impl_item| {
                                switch (impl_item) {
                                    .proc_decl => |proc| {
                                        if (proc.path.len == event.path.len) {
                                            var matches = true;
                                            for (proc.path, 0..) |seg, j| {
                                                if (!eql(seg, event.path[j])) {
                                                    matches = false;
                                                    break;
                                                }
                                            }
                                            if (matches) {
                                                pos = writeStr(&buffer, pos, "            _ = &e;\n");
                                                pos = writeStr(&buffer, pos, proc.body);
                                                pos = writeStr(&buffer, pos, "\n");
                                                found_impl = true;
                                                break;
                                            }
                                        }
                                    },
                                    else => {},
                                }
                            }
                            
                            if (!found_impl) {
                                if (event.branches.len > 0) {
                                    pos = writeStr(&buffer, pos, "            return .{ .");
                                    pos = writeStr(&buffer, pos, event.branches[0].name);
                                    pos = writeStr(&buffer, pos, " = .{} };\n");
                                } else {
                                    pos = writeStr(&buffer, pos, "            return undefined;\n");
                                }
                            }
                            
                            pos = writeStr(&buffer, pos, "        }\n");
                            pos = writeStr(&buffer, pos, "    };\n");
                        },
                        else => {},
                    }
                }
                
                // Close the module struct
                pos = writeStr(&buffer, pos, "};\n\n");
            },
            else => {},
        }
    }
    
    // Now generate the main module struct
    pos = writeStr(&buffer, pos, "pub const main_module = struct {\n");
    
    // First pass: Collect zig_lines (imports) - inside the module struct!
    for (e.ast.items) |item| {
        switch (item) {
            .module_decl => continue,  // Skip module declarations
            .zig_line => |line| {
                pos = writeStr(&buffer, pos, "    ");
                pos = writeStr(&buffer, pos, line.content);
                pos = writeStr(&buffer, pos, "\n");
            },
            else => {},
        }
    }
    
    // Second pass: Generate events (only local ones, not imported)
    for (e.ast.items) |item| {
        switch (item) {
            .module_decl => continue,  // Skip module declarations
            .event_decl => |event| {
                // Skip compiler events
                if (event.path.len > 0 and eql(event.path[0], "compiler")) {
                    continue;
                }
                
                // Write the event with proper indentation (we're inside main_module)
                pos = writeStr(&buffer, pos, "    pub const ");
                pos = writeStr(&buffer, pos, event.path[event.path.len - 1]);
                pos = writeStr(&buffer, pos, " = struct {\n");
                
                // Input struct
                pos = writeStr(&buffer, pos, "        pub const Input = struct {\n");
                for (event.input.fields) |field| {
                    pos = writeStr(&buffer, pos, "            ");
                    pos = writeStr(&buffer, pos, field.name);
                    pos = writeStr(&buffer, pos, ": ");
                    if (field.is_file or field.is_embed_file) {
                        pos = writeStr(&buffer, pos, "[]const u8");
                    } else {
                        pos = writeStr(&buffer, pos, field.type);
                    }
                    pos = writeStr(&buffer, pos, ",\n");
                }
                pos = writeStr(&buffer, pos, "        };\n");
                
                // Output union
                pos = writeStr(&buffer, pos, "        pub const Output = union(enum) {\n");
                for (event.branches) |branch| {
                    pos = writeStr(&buffer, pos, "            ");
                    pos = writeStr(&buffer, pos, branch.name);
                    pos = writeStr(&buffer, pos, ": struct {\n");
                    for (branch.payload.fields) |field| {
                        pos = writeStr(&buffer, pos, "                ");
                        pos = writeStr(&buffer, pos, field.name);
                        pos = writeStr(&buffer, pos, ": ");
                        pos = writeStr(&buffer, pos, field.type);
                        pos = writeStr(&buffer, pos, ",\n");
                    }
                    pos = writeStr(&buffer, pos, "            },\n");
                }
                pos = writeStr(&buffer, pos, "        };\n");
                
                // Handler function
                pos = writeStr(&buffer, pos, "        pub fn handler(e: Input) Output {\n");
                
                // Find implementation
                var found_impl = false;
                for (e.ast.items) |impl_item| {
                    switch (impl_item) {
                        .proc_decl => |proc| {
                            if (proc.path.len == event.path.len) {
                                var matches = true;
                                for (proc.path, 0..) |seg, j| {
                                    if (!eql(seg, event.path[j])) {
                                        matches = false;
                                        break;
                                    }
                                }
                                if (matches) {
                                    pos = writeStr(&buffer, pos, "            _ = &e;\n");
                                    pos = writeStr(&buffer, pos, proc.body);
                                    pos = writeStr(&buffer, pos, "\n");
                                    found_impl = true;
                                    break;
                                }
                            }
                        },
                        .subflow_impl => |subflow| {
                            if (subflow.event_path.len == event.path.len) {
                                var matches = true;
                                for (subflow.event_path, 0..) |seg, j| {
                                    if (!eql(seg, event.path[j])) {
                                        matches = false;
                                        break;
                                    }
                                }
                                if (matches) {
                                    switch (subflow.body) {
                                        .immediate => |bc| {
                                            pos = writeStr(&buffer, pos, "            return .{ .");
                                            pos = writeStr(&buffer, pos, bc.branch_name);
                                            pos = writeStr(&buffer, pos, " = .{");
                                            for (bc.fields, 0..) |field, k| {
                                                if (k > 0) pos = writeStr(&buffer, pos, ", ");
                                                pos = writeStr(&buffer, pos, " .");
                                                pos = writeStr(&buffer, pos, field.name);
                                                pos = writeStr(&buffer, pos, " = ");
                                                pos = writeStr(&buffer, pos, field.type);
                                            }
                                            pos = writeStr(&buffer, pos, " } };\n");
                                        },
                                        .flow => {
                                            pos = writeStr(&buffer, pos, "            // Flow subflow\n");
                                            pos = writeStr(&buffer, pos, "            return undefined;\n");
                                        },
                                    }
                                    found_impl = true;
                                    break;
                                }
                            }
                        },
                        else => {},
                    }
                }
                
                if (!found_impl) {
                    if (event.branches.len > 0) {
                        pos = writeStr(&buffer, pos, "            return .{ .");
                        pos = writeStr(&buffer, pos, event.branches[0].name);
                        pos = writeStr(&buffer, pos, " = .{} };\n");
                    } else {
                        pos = writeStr(&buffer, pos, "            return undefined;\n");
                    }
                }
                
                pos = writeStr(&buffer, pos, "        }\n");
                
                // Close the event struct
                pos = writeStr(&buffer, pos, "    };\n");
            },
            else => {},
        }
    }
    
    // Generate flows as functions inside main_module
    var flow_counter: usize = 0;
    for (e.ast.items) |item| {
        switch (item) {
            .flow => |flow| {
                pos = writeStr(&buffer, pos, "    pub fn flow");
                // Simple number writing
                if (flow_counter == 0) {
                    pos = writeStr(&buffer, pos, "0");
                } else if (flow_counter == 1) {
                    pos = writeStr(&buffer, pos, "1");
                } else if (flow_counter == 2) {
                    pos = writeStr(&buffer, pos, "2");
                } else if (flow_counter == 3) {
                    pos = writeStr(&buffer, pos, "3");
                } else if (flow_counter == 4) {
                    pos = writeStr(&buffer, pos, "4");
                } else {
                    pos = writeStr(&buffer, pos, "N");
                }
                pos = writeStr(&buffer, pos, "() void {\n");
                
                // Generate the flow body
                pos = writeStr(&buffer, pos, "        const result = ");
                
                // Check if this event is in a module or main
                var event_module: ?[]const u8 = null;
                
                // First check modules
                for (e.ast.items) |evt_item| {
                    switch (evt_item) {
                        .module_decl => |module| {
                            for (module.items) |mod_item| {
                                switch (mod_item) {
                                    .event_decl => |event| {
                                        if (event.path.len == flow.invocation.path.len) {
                                            var matches = true;
                                            for (event.path, 0..) |seg, j| {
                                                if (!eql(seg, flow.invocation.path[j])) {
                                                    matches = false;
                                                    break;
                                                }
                                            }
                                            if (matches) {
                                                event_module = module.logical_name;
                                                break;
                                            }
                                        }
                                    },
                                    else => {},
                                }
                            }
                            if (event_module != null) break;
                        },
                        else => {},
                    }
                }
                
                // Use module prefix if imported, otherwise local
                if (event_module) |mod| {
                    pos = writeStr(&buffer, pos, mod);
                    pos = writeStr(&buffer, pos, ".");
                    pos = writeStr(&buffer, pos, flow.invocation.path[flow.invocation.path.len - 1]);
                } else {
                    pos = writeStr(&buffer, pos, flow.invocation.path[flow.invocation.path.len - 1]);
                }
                pos = writeStr(&buffer, pos, ".handler(.{");
                
                for (flow.invocation.args, 0..) |arg, i| {
                    if (i > 0) pos = writeStr(&buffer, pos, ", ");
                    pos = writeStr(&buffer, pos, " .");
                    pos = writeStr(&buffer, pos, arg.name);
                    pos = writeStr(&buffer, pos, " = ");
                    pos = writeStr(&buffer, pos, arg.value);
                }
                pos = writeStr(&buffer, pos, " });\n");
                
                // Handle the result (simplified for now)
                pos = writeStr(&buffer, pos, "        switch (result) {\n");
                
                // Find the event to get branch names (check both modules and main)
                var found_event = false;
                for (e.ast.items) |evt_item| {
                    switch (evt_item) {
                        .module_decl => |module| {
                            for (module.items) |mod_item| {
                                switch (mod_item) {
                                    .event_decl => |event| {
                                        if (event.path.len == flow.invocation.path.len) {
                                            var matches = true;
                                            for (event.path, 0..) |seg, j| {
                                                if (!eql(seg, flow.invocation.path[j])) {
                                                    matches = false;
                                                    break;
                                                }
                                            }
                                            if (matches) {
                                                for (event.branches) |branch| {
                                                    pos = writeStr(&buffer, pos, "            .");
                                                    pos = writeStr(&buffer, pos, branch.name);
                                                    pos = writeStr(&buffer, pos, " => |v| {\n");
                                                    pos = writeStr(&buffer, pos, "                _ = v; // Terminal\n");
                                                    pos = writeStr(&buffer, pos, "            },\n");
                                                }
                                                found_event = true;
                                                break;
                                            }
                                        }
                                    },
                                    else => {},
                                }
                            }
                            if (found_event) break;
                        },
                        .event_decl => |event| {
                            if (event.path.len == flow.invocation.path.len) {
                                var matches = true;
                                for (event.path, 0..) |seg, j| {
                                    if (!eql(seg, flow.invocation.path[j])) {
                                        matches = false;
                                        break;
                                    }
                                }
                                if (matches) {
                                    for (event.branches) |branch| {
                                        pos = writeStr(&buffer, pos, "            .");
                                        pos = writeStr(&buffer, pos, branch.name);
                                        pos = writeStr(&buffer, pos, " => |v| {\n");
                                        pos = writeStr(&buffer, pos, "                _ = v; // Terminal\n");
                                        pos = writeStr(&buffer, pos, "            },\n");
                                    }
                                    found_event = true;
                                    break;
                                }
                            }
                        },
                        else => {},
                    }
                    if (found_event) break;
                }
                
                pos = writeStr(&buffer, pos, "        }\n");
                pos = writeStr(&buffer, pos, "    }\n\n");
                
                flow_counter += 1;
            },
            else => {},
        }
    }
    
    // Close the main_module struct
    pos = writeStr(&buffer, pos, "};\n\n");
    
    // Generate minimal main function that calls flows from main_module
    pos = writeStr(&buffer, pos, "pub fn main() void {\n");
    
    var flow_count: usize = 0;
    for (e.ast.items) |item| {
        switch (item) {
            .flow => {
                pos = writeStr(&buffer, pos, "    main_module.flow");
                if (flow_count == 0) {
                    pos = writeStr(&buffer, pos, "0");
                } else if (flow_count == 1) {
                    pos = writeStr(&buffer, pos, "1");
                } else if (flow_count == 2) {
                    pos = writeStr(&buffer, pos, "2");
                } else if (flow_count == 3) {
                    pos = writeStr(&buffer, pos, "3");
                } else if (flow_count == 4) {
                    pos = writeStr(&buffer, pos, "4");
                } else {
                    pos = writeStr(&buffer, pos, "N");
                }
                pos = writeStr(&buffer, pos, "();\n");
                flow_count += 1;
            },
            else => {},
        }
    }
    
    pos = writeStr(&buffer, pos, "}\n");
    
    // Return the emitted code!
    const final_code = buffer[0..pos];
    return .{ .emitted = .{ .code = final_code } };
    }
};

// Bootstrap coordinator - now calls the REAL compiler.emit.zig!
const compiler_coordinate_default = struct {
    pub const Input = struct { ast: *const SourceFile };
    pub const Output = union(enum) {
        coordinated: struct {
            ast: *const SourceFile,
            code: []const u8, 
            metrics: []const u8,
        },
    };
    
    pub fn handler(e: Input) Output {
        // Call the REAL compiler.emit.zig that was generated above!
        const emit_result = compiler_emit_zig.handler(.{ .ast = e.ast });
        
        return .{ .coordinated = .{
            .ast = e.ast,
            .code = emit_result.emitted.code,
            .metrics = "Metacircular compilation complete!",
        }};
    }
};
// Compile-time code generation
const ComptimeEmitter = struct {
    pub fn emit(ast: *const SourceFile) [64*1024]u8 {
        @setEvalBranchQuota(100000);  // Increase branch quota for complex ASTs
        const result = compiler_coordinate_default.handler(.{ .ast = ast });
        var buf: [64*1024]u8 = [_]u8{0} ** (64*1024);
        const copy_len = @min(result.coordinated.code.len, 64*1024);
        @memcpy(buf[0..copy_len], result.coordinated.code[0..copy_len]);
        return buf;
    }
};

// Generate code at compile-time from the AST
const generated_code_buffer = ComptimeEmitter.emit(&PROGRAM_AST);
// For now, just use the full buffer - we'll trim zeros at runtime
const generated_code = generated_code_buffer[0..];

// Standard library import for the backend
const std = @import("std");
// === KORU BACKEND CODE GENERATOR ===
// This outputs the final Zig code generated by compiler.emit.zig

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();
    defer _ = gpa.deinit();
    
    // Get the output filename from argv (passed from koruc)
    const args = try std.process.argsAlloc(allocator);
    defer std.process.argsFree(allocator, args);
    
    // Default output names
    const emitted_file = "output_emitted.zig";
    const output_exe = if (args.len > 1) args[1] else "a.out";
    
    // Find actual length (trim trailing zeros)
    var actual_len: usize = generated_code.len;
    while (actual_len > 0 and generated_code[actual_len - 1] == 0) {
        actual_len -= 1;
    }
    const trimmed_code = generated_code[0..actual_len];
    
    // Write the generated code to a file
    const file = try std.fs.cwd().createFile(emitted_file, .{});
    defer file.close();
    try file.writeAll(trimmed_code);
    
    // Report what we generated
    const stdout = std.fs.File.stdout();
    var buf: [512]u8 = undefined;
    const msg = try std.fmt.bufPrint(&buf, "✓ Generated {s} ({d} bytes)\n", .{emitted_file, actual_len});
    try stdout.writeAll(msg);
    
    // Now compile the emitted code  
    var emit_path_buf: [256]u8 = undefined;
    const emit_path = try std.fmt.bufPrint(&emit_path_buf, "-femit-bin={s}", .{output_exe});
    const argv = [_][]const u8{ "zig", "build-exe", emitted_file, emit_path };
    const result = std.process.Child.run(.{
        .allocator = allocator,
        .argv = &argv,
    }) catch |err| {
        const stderr = std.fs.File.stderr();
        var err_buf: [512]u8 = undefined;
        const err_msg = try std.fmt.bufPrint(&err_buf, "✗ Failed to spawn zig compiler: {}\n", .{err});
        try stderr.writeAll(err_msg);
        std.process.exit(1);
    };
    defer allocator.free(result.stdout);
    defer allocator.free(result.stderr);
    
    const stdout2 = std.fs.File.stdout();
    var buf2: [512]u8 = undefined;
    if (result.term.Exited == 0) {
        const msg2 = try std.fmt.bufPrint(&buf2, "✓ Compiled to {s}\n", .{output_exe});
        try stdout2.writeAll(msg2);
    } else {
        const msg2 = try std.fmt.bufPrint(&buf2, "✗ Compilation failed\n", .{});
        try stdout2.writeAll(msg2);
        if (result.stderr.len > 0) {
            var err_buf2: [1024]u8 = undefined;
            const err_msg2 = try std.fmt.bufPrint(&err_buf2, "Error: {s}\n", .{result.stderr});
            try std.fs.File.stderr().writeAll(err_msg2);
        }
        std.process.exit(1);
    }
}