// Generated by Koru compiler.emit.zig event - METACIRCULAR!

pub const io = struct {
    // Koru Standard Library: I/O
    // Basic input/output operations for Koru programs
    //
    // Finally! After achieving consciousness (metacircular compilation),
    // we can now print "Hello, World!" 
    const std = @import("std");
    // Print text without newline
    pub const print = struct {
        pub const Input = struct {
            text: []const u8,
        };
        pub const Output = union(enum) {
            printed: struct {
            },
        };
        pub fn handler(e: Input) Output {
            _ = &e;

    std.debug.print("{s}", .{e.text});
    return .{ .printed = .{} };
        }
    };
    // Print text with newline
    pub const println = struct {
        pub const Input = struct {
            text: []const u8,
        };
        pub const Output = union(enum) {
            printed: struct {
            },
            failed: struct {
                message: []const u8,
            },
        };
        pub fn handler(e: Input) Output {
            _ = &e;

    std.debug.print("{s}\n", .{e.text});
    return .{ .printed = .{} };
        }
    };
    // Print formatted text
    // NOTE: printf with varargs would require runtime support - skipping for now
    // ~pub event io.printf { format: []const u8, args: anytype }
    // ~proc io.printf {
    //     std.debug.print(e.format, e.args);
    //     return .{ .printed = .{} };
    // }
    // Read line from stdin (for future interactive programs)
    pub const readln = struct {
        pub const Input = struct {
        };
        pub const Output = union(enum) {
            line: struct {
                text: []const u8,
            },
            eof: struct {
            },
            failed: struct {
                message: []const u8,
            },
        };
        pub fn handler(e: Input) Output {
            _ = &e;

    // TODO: Implement actual stdin reading
    // For now, return a placeholder
    return .{ .failed = .{ .message = "io.readln not yet implemented" } };
        }
    };
    // Debug print for development
    // NOTE: debug with anytype would require runtime support - skipping for now
    // ~pub event io.debug { label: []const u8, value: anytype }
    // ~proc io.debug {
    //     std.debug.print("[DEBUG {s}]: ", .{e.label});
    //     std.debug.print("{any}\n", .{e.value});
    //     return .{ .printed = .{} };
    // }
    // Print error to stderr
    pub const eprintln = struct {
        pub const Input = struct {
            message: []const u8,
        };
        pub const Output = union(enum) {
            printed: struct {
            },
        };
        pub fn handler(e: Input) Output {
            _ = &e;

    const stderr = std.io.getStdErr().writer();
    stderr.print("ERROR: {s}\n", .{e.message}) catch {
        // Fall back to debug print if stderr fails
        std.debug.print("ERROR: {s}\n", .{e.message});
    };
    return .{ .printed = .{} };
        }
    };
    // Success message with green color (if terminal supports it)
    pub const success = struct {
        pub const Input = struct {
            message: []const u8,
        };
        pub const Output = union(enum) {
            printed: struct {
            },
        };
        pub fn handler(e: Input) Output {
            _ = &e;

    std.debug.print("✅ {s}\n", .{e.message});
    return .{ .printed = .{} };
        }
    };
    // Warning message
    pub const warn = struct {
        pub const Input = struct {
            message: []const u8,
        };
        pub const Output = union(enum) {
            printed: struct {
            },
        };
        pub fn handler(e: Input) Output {
            _ = &e;

    std.debug.print("⚠️  {s}\n", .{e.message});
    return .{ .printed = .{} };
        }
    };
};

pub const main_module = struct {
    // Simplified Koru Compiler Library
    // A working implementation that can actually be injected and used
    // ============================================================
    // ARCHITECTURAL CONSTRAINT: NO INLINE FLOWS IN COMPILER PROCS
    // ============================================================
    // Compiler procs (compiler.*) MUST be pure Zig code.
    // They CANNOT use inline flows (~event syntax) because:
    // 
    // 1. They run at Zig compile-time (no Koru runtime exists)
    // 2. The compiler that processes flows doesn't exist yet
    // 3. This is the bootstrap - it must be minimal and simple
    //
    // This is NOT a limitation but a FEATURE - it keeps the
    // metacircular foundation small, simple, and trustworthy.
    // 
    // User code can use ALL Koru features. Only the compiler
    // itself is restricted to pure Zig, which is perfect for
    // the string manipulation and AST walking it needs to do.
    // ============================================================
    // The default compiler coordinator
    // Zig code emission event - the final step of compilation!
    // Implementation of Zig code emission - this IS ComptimeEmitter as a Koru proc!
    // Updated coordinator that calls emission!
    // Tour 01: Branches and Control Flow with I/O
    // This demonstrates event branches and importing
    // Import I/O for printing
    // Import std for this module (each module needs its own)
    const std = @import("std");
    // Event that processes a greeting request
    // Proc that decides how to greet based on the name
    // Main flow - demonstrate different branches
    pub const process_greeting = struct {
        pub const Input = struct {
            name: []const u8,
        };
        pub const Output = union(enum) {
            friendly: struct {
                msg: []const u8,
            },
            formal: struct {
                msg: []const u8,
            },
            unknown: struct {
            },
        };
        pub fn handler(e: Input) Output {
            _ = &e;

    
    // Check the name and return different branches
    if (std.mem.eql(u8, e.name, "friend")) {
        return .{ .friendly = .{ .msg = "Hey buddy! 👋" }};
    } else if (std.mem.eql(u8, e.name, "boss")) {
        return .{ .formal = .{ .msg = "Good day, sir/madam." }};
    } else if (e.name.len == 0) {
        return .{ .unknown = .{} };
    } else {
        // Generic friendly greeting for everyone else
        return .{ .friendly = .{ .msg = "Hello there!" }};
    }
        }
    };
    pub fn flow0() void {
        const result = process_greeting.handler(.{ .name = "friend" });
        switch (result) {
            .friendly => |v| {
                _ = v; // Terminal
            },
            .formal => |v| {
                _ = v; // Terminal
            },
            .unknown => |v| {
                _ = v; // Terminal
            },
        }
    }

};

pub fn main() void {
    main_module.flow0();
}
