// Generated intermediate file for: tests/integration/07_namespaces.kz
// This file contains the serialized AST and generates code at compile-time

// Generated by Koru AST Serializer
// This file contains the complete program AST as Zig data structures

// AST Type Definitions

const SourceFile = struct {
    items: []const Item,
};

const Item = union(enum) {
    zig_line: []const u8,
    event_decl: EventDecl,
    proc_decl: ProcDecl,
    flow: Flow,
    import_decl: ImportDecl,
    subflow_impl: SubflowImpl,
    label_decl: LabelDecl,
};

const EventDecl = struct {
    path: []const []const u8,
    input: Shape,
    branches: []const Branch,
    is_public: bool,
};

const Shape = struct {
    fields: []const Field,
};

const Field = struct {
    name: []const u8,
    type: []const u8,
    is_flow_ast: bool,
    is_source: bool,
    is_file: bool,
    phantom: ?[]const u8,
};

const Branch = struct {
    name: []const u8,
    payload: Shape,
    is_deferred: bool,
};

const ProcDecl = struct {
    path: []const []const u8,
    body: []const u8,  // The Zig code body
};

const Flow = struct {
    invocation: Invocation,
    continuations: []const Continuation,
    pre_label: ?[]const u8,
    post_label: ?[]const u8,
};

const Invocation = struct {
    path: []const []const u8,
    args: []const Arg,
};

const Arg = struct {
    name: []const u8,
    value: []const u8,
    ast_value: ?*const FlowAST,
};

const FlowAST = struct {
    flows: []const Flow,
};

const Continuation = struct {
    branch: []const u8,
    binding: ?[]const u8,
    pipeline: []const Step,
    indent: usize,
    nested: []const Continuation,
};

const Step = union(enum) {
    invocation: Invocation,
    label_apply: []const u8,
    label_with_invocation: struct {
        label: []const u8,
        invocation: Invocation,
    },
    terminal: void,
    deref: struct {
        target: []const u8,
        args: ?[]const Arg,
    },
    branch_constructor: BranchConstructor,
};

const BranchConstructor = struct {
    branch_name: []const u8,
    fields: []const Field,
};

const ImportDecl = struct {
    path: []const u8,
    name: ?[]const u8,
};

const SubflowImpl = struct {
    event_path: []const []const u8,
    body: SubflowBody,
};

const SubflowBody = union(enum) {
    flow: Flow,
    immediate: BranchConstructor,
};

const LabelDecl = struct {
    name: []const u8,
    continuations: []const Continuation,
};

pub const PROGRAM_AST = SourceFile{
    .items = &[_]Item{
        .{ .zig_line = "// Simplified Koru Compiler Library" },
        .{ .zig_line = "// A working implementation that can actually be injected and used" },
        .{ .zig_line = "// The default compiler coordinator" },
        .{ .event_decl = EventDecl{
            .path = &[_][]const u8{"compiler", "coordinate", "default"},
            .input = Shape{ .fields = &[_]Field{
                Field{ .name = "ast", .type = "ProgramAST", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
            } },
            .branches = &[_]Branch{
                Branch{
                    .name = "coordinated",
                    .payload = Shape{ .fields = &[_]Field{
                        Field{ .name = "ast", .type = "ProgramAST", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
                        Field{ .name = "metrics", .type = "[]const u8", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
                    } },
                    .is_deferred = false,
                },
            },
            .is_public = true,
        } },
        .{ .zig_line = "// Implementation that analyzes the AST" },
        .{ .zig_line = "// For now, just return enhanced metrics (until compile-time execution works)" },
        .{ .zig_line = "// In the future, this will actually count events and transform the AST" },
        .{ .subflow_impl = SubflowImpl{
            .event_path = &[_][]const u8{"compiler", "coordinate", "default"},
            .body = .{ .immediate = BranchConstructor{
                .branch_name = "coordinated",
                .fields = &[_]Field{
                    Field{ .name = "metrics", .type = "\"Default Koru compiler: Ready for transforms!\"", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
                },
            } },
        } },
        .{ .zig_line = "// Minimal test for namespace duplication bug" },
        .{ .event_decl = EventDecl{
            .path = &[_][]const u8{"foo", "bar"},
            .input = Shape{ .fields = &[_]Field{
                Field{ .name = "x", .type = "u32", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
            } },
            .branches = &[_]Branch{
                Branch{
                    .name = "ok",
                    .payload = Shape{ .fields = &[_]Field{
                        Field{ .name = "result", .type = "u32", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
                    } },
                    .is_deferred = false,
                },
            },
            .is_public = false,
        } },
        .{ .event_decl = EventDecl{
            .path = &[_][]const u8{"foo", "baz"},
            .input = Shape{ .fields = &[_]Field{
                Field{ .name = "y", .type = "u32", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
            } },
            .branches = &[_]Branch{
                Branch{
                    .name = "done",
                    .payload = Shape{ .fields = &[_]Field{
                        Field{ .name = "value", .type = "u32", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
                    } },
                    .is_deferred = false,
                },
            },
            .is_public = false,
        } },
        .{ .proc_decl = ProcDecl{
            .path = &[_][]const u8{"foo", "bar"},
            .body = 
                \\
                \\    return .{ .@"ok" = .{ .result = e.x + 1 } };,
        } },
        .{ .proc_decl = ProcDecl{
            .path = &[_][]const u8{"foo", "baz"},
            .body = 
                \\
                \\    return .{ .@"done" = .{ .value = e.y * 2 } };,
        } },
        .{ .zig_line = "// Main flow to test namespace handling" },
        .{ .zig_line = "// [Functional] Inlined from foo.bar\n{\n    // Bind parameters\n    const e = .{\n        .x = 10,\n    };\n\n    // Inlined body\n    return .{ .@\"ok\" = .{ .result = e.x + 1 } };\n\n    // Handle continuations\n    // Branch: ok (bound to: r)\n}\n" },
        .{ .subflow_impl = SubflowImpl{
            .event_path = &[_][]const u8{"compiler", "coordinate"},
            .body = .{ .immediate = BranchConstructor{
                .branch_name = "coordinated",
                .fields = &[_]Field{
                    Field{ .name = "ast", .type = "e.ast", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
                    Field{ .name = "metrics", .type = "\"Bootstrap compiler (library included)\"", .is_flow_ast = false, .is_source = false, .is_file = false, .phantom = null },
                },
            } },
        } },
    },
};


// Compile-time code generation
const ComptimeEmitter = struct {
    const MAX_SIZE = 64 * 1024; // 64KB should be enough
    
    pub fn emit(ast: *const SourceFile) [MAX_SIZE]u8 {
        var buffer: [MAX_SIZE]u8 = undefined;
        var pos: usize = 0;
        
        // Write header
        pos = writeStr(&buffer, pos, "// Generated by Koru Metacircular Compilation!\\n");
        pos = writeStr(&buffer, pos, "const std = @import(\\\"std\\\");\\n\\n");
        
        // First pass: Generate event structs from declarations
        for (ast.items) |item| {
            switch (item) {
                .zig_line => |line| {
                    // Pass through top-level Zig code
                    pos = writeStr(&buffer, pos, line);
                    pos = writeStr(&buffer, pos, "\\n");
                },
                .event_decl => |event| {
                    // Generate event struct
                    pos = writeStr(&buffer, pos, "pub const ");
                    pos = writePath(&buffer, pos, event.path);
                    pos = writeStr(&buffer, pos, " = struct {\\n");
                    
                    // Input struct
                    pos = writeStr(&buffer, pos, "    pub const Input = struct {\\n");
                    for (event.input.fields) |field| {
                        pos = writeStr(&buffer, pos, "        ");
                        pos = writeStr(&buffer, pos, field.name);
                        pos = writeStr(&buffer, pos, ": ");
                        // Handle File type - convert to []const u8 for compile-time embedding
                        if (field.is_file) {
                            pos = writeStr(&buffer, pos, "[]const u8");
                        } else {
                            pos = writeStr(&buffer, pos, field.type);
                        }
                        pos = writeStr(&buffer, pos, ",\\n");
                    }
                    pos = writeStr(&buffer, pos, "    };\\n");
                    
                    // Output union
                    pos = writeStr(&buffer, pos, "    pub const Output = union(enum) {\\n");
                    for (event.branches) |branch| {
                        pos = writeStr(&buffer, pos, "        ");
                        pos = writeStr(&buffer, pos, branch.name);
                        pos = writeStr(&buffer, pos, ": struct {\\n");
                        for (branch.payload.fields) |field| {
                            pos = writeStr(&buffer, pos, "            ");
                            pos = writeStr(&buffer, pos, field.name);
                            pos = writeStr(&buffer, pos, ": ");
                            pos = writeStr(&buffer, pos, field.type);
                            pos = writeStr(&buffer, pos, ",\\n");
                        }
                        pos = writeStr(&buffer, pos, "        },\\n");
                    }
                    pos = writeStr(&buffer, pos, "    };\\n");
                    
                    // Check if this event has FlowAST parameters
                    var has_flow_ast = false;
                    for (event.input.fields) |field| {
                        if (field.is_flow_ast) {
                            has_flow_ast = true;
                            break;
                        }
                    }
                    
                    // Generate appropriate handler based on whether we have FlowAST
                    if (has_flow_ast) {
                        // Generate two-layer handler for FlowAST transformation
                        pos = writeStr(&buffer, pos, "    // Enhanced handler for FlowAST transformation\\n");
                        pos = writeStr(&buffer, pos, "    pub fn handler_comptime(e: Input, program_ast: *const SourceFile) struct { output: Output, new_ast: ?SourceFile } {\\n");
                    } else {
                        // Regular handler for non-FlowAST events
                        pos = writeStr(&buffer, pos, "    pub fn handler(e: Input) Output {\\n");
                    }
                    
                    // First look for matching subflow
                    var found_impl = false;
                    for (ast.items) |impl_item| {
                        switch (impl_item) {
                            .subflow_impl => |subflow| {
                                // Check if paths match
                                if (subflow.event_path.len == event.path.len) {
                                    var matches = true;
                                    for (subflow.event_path, 0..) |seg, j| {
                                        if (!eql(seg, event.path[j])) {
                                            matches = false;
                                            break;
                                        }
                                    }
                                    if (matches) {
                                        // Found matching subflow, emit its body inline
                                        switch (subflow.body) {
                                            .immediate => |bc| {
                                                pos = writeStr(&buffer, pos, "        return .{ .");
                                                pos = writeStr(&buffer, pos, bc.branch_name);
                                                pos = writeStr(&buffer, pos, " = .{");
                                                for (bc.fields, 0..) |field, k| {
                                                    if (k > 0) pos = writeStr(&buffer, pos, ", ");
                                                    pos = writeStr(&buffer, pos, " .");
                                                    pos = writeStr(&buffer, pos, field.name);
                                                    pos = writeStr(&buffer, pos, " = ");
                                                    pos = writeStr(&buffer, pos, field.type);
                                                }
                                                pos = writeStr(&buffer, pos, " } };\\n");
                                            },
                                            .flow => {
                                                // TODO: Handle flow-based subflows
                                                pos = writeStr(&buffer, pos, "        // TODO: Flow-based subflow\\n");
                                                pos = writeStr(&buffer, pos, "        return undefined;\\n");
                                            },
                                        }
                                        found_impl = true;
                                        break;
                                    }
                                }
                            },
                            .proc_decl => |proc| {
                                // Check if paths match
                                if (!found_impl and proc.path.len == event.path.len) {
                                    var matches = true;
                                    for (proc.path, 0..) |seg, j| {
                                        if (!eql(seg, event.path[j])) {
                                            matches = false;
                                            break;
                                        }
                                    }
                                    if (matches) {
                                        // Found matching proc, emit its body
                                        if (has_flow_ast) {
                                            // For FlowAST handlers, wrap the body to return the proper struct
                                            pos = writeStr(&buffer, pos, "        // User proc body with PROGRAM_AST access\\n");
                                            pos = writeStr(&buffer, pos, "        const user_output = ");
                                            pos = writeStr(&buffer, pos, proc.body);
                                            pos = writeStr(&buffer, pos, "\\n");
                                            pos = writeStr(&buffer, pos, "        // Wrap in enhanced result\\n");
                                            pos = writeStr(&buffer, pos, "        return .{ .output = user_output, .new_ast = null };\\n");
                                        } else {
                                            // Regular proc body
                                            pos = writeStr(&buffer, pos, proc.body);
                                            pos = writeStr(&buffer, pos, "\\n");
                                        }
                                        found_impl = true;
                                        break;
                                    }
                                }
                            },
                            else => {},
                        }
                    }
                    
                    if (!found_impl) {
                        // No implementation found, use default
                        if (event.branches.len > 0) {
                            pos = writeStr(&buffer, pos, "        return .{ .");
                            pos = writeStr(&buffer, pos, event.branches[0].name);
                            pos = writeStr(&buffer, pos, " = .{} };\\n");
                        } else {
                            pos = writeStr(&buffer, pos, "        return undefined;\\n");
                        }
                    }
                    
                    pos = writeStr(&buffer, pos, "    }\\n");
                    
                    // If this was a FlowAST handler, generate the runtime wrapper
                    if (has_flow_ast) {
                        pos = writeStr(&buffer, pos, "\\n");
                        pos = writeStr(&buffer, pos, "    // Runtime wrapper that calls comptime handler\\n");
                        pos = writeStr(&buffer, pos, "    pub fn handler(e: Input) Output {\\n");
                        pos = writeStr(&buffer, pos, "        const result = handler_comptime(e, &PROGRAM_AST);\\n");
                        pos = writeStr(&buffer, pos, "        // TODO: Collect AST transformations\\n");
                        pos = writeStr(&buffer, pos, "        return result.output;\\n");
                        pos = writeStr(&buffer, pos, "    }\\n");
                    }
                    
                    pos = writeStr(&buffer, pos, "};\\n\\n");
                },
                .subflow_impl => {
                    // Subflows are now integrated directly into event handlers
                },
                else => {},
            }
        }
        
        // Generate main function from top-level flows
        var has_flows = false;
        var flow_counter: usize = 0;
        for (ast.items) |item| {
            switch (item) {
                .flow => {
                    if (!has_flows) {
                        pos = writeStr(&buffer, pos, "\\npub fn main() void {\\n");
                        pos = writeStr(&buffer, pos, "    std.debug.print(\\\"Executing Koru flows...\\\\n\\\", .{});\\n");
                        has_flows = true;
                    }
                    
                    // Check if flow has a label
                    if (item.flow.post_label) |label| {
                        // Generate label function first
                        pos = writeStr(&buffer, pos, "    const __label_");
                        pos = writeStr(&buffer, pos, label);
                        pos = writeStr(&buffer, pos, " = struct {\\n");
                        pos = writeStr(&buffer, pos, "        fn apply(out: ");
                        pos = writePath(&buffer, pos, item.flow.invocation.path);
                        pos = writeStr(&buffer, pos, ".Output) void {\\n");
                        pos = writeStr(&buffer, pos, "            switch (out) {\\n");
                        
                        // Generate continuations
                        for (item.flow.continuations) |cont| {
                            pos = writeStr(&buffer, pos, "                .@\\\"");
                            pos = writeStr(&buffer, pos, cont.branch);
                            pos = writeStr(&buffer, pos, "\\\" => |");
                            if (cont.binding) |binding| {
                                if (eql(binding, "->")) {
                                    pos = writeStr(&buffer, pos, "_");
                                } else {
                                    pos = writeStr(&buffer, pos, binding);
                                }
                            } else {
                                pos = writeStr(&buffer, pos, "_");
                            }
                            pos = writeStr(&buffer, pos, "| {\\n");
                            
                            // Check for loop jump in pipeline or nested continuations
                            var has_jump = false;
                            
                            // First check the main pipeline
                            for (cont.pipeline) |step| {
                                switch (step) {
                                    .label_apply => |target| {
                                        if (eql(target, label)) {
                                            has_jump = true;
                                            // Generate the recursive call
                                            // First call the invocation if present
                                            for (cont.pipeline) |prev_step| {
                                                switch (prev_step) {
                                                    .invocation => |inv| {
                                                        pos = writeStr(&buffer, pos, "                    const next_out = ");
                                                        pos = writePath(&buffer, pos, inv.path);
                                                        pos = writeStr(&buffer, pos, ".handler(.{ ");
                                                        
                                                        // Find the event declaration for File type checking
                                                        var inv_event: ?*const EventDecl = null;
                                                        for (ast.items) |ast_item| {
                                                            switch (ast_item) {
                                                                .event_decl => |*event| {
                                                                    if (event.path.len == inv.path.len) {
                                                                        var matches = true;
                                                                        for (event.path, 0..) |seg, k| {
                                                                            if (!eql(seg, inv.path[k])) {
                                                                                matches = false;
                                                                                break;
                                                                            }
                                                                        }
                                                                        if (matches) {
                                                                            inv_event = event;
                                                                            break;
                                                                        }
                                                                    }
                                                                },
                                                                else => {},
                                                            }
                                                        }
                                                        
                                                        for (inv.args, 0..) |arg, j| {
                                                            if (j > 0) pos = writeStr(&buffer, pos, ", ");
                                                            pos = writeStr(&buffer, pos, ".");
                                                            pos = writeStr(&buffer, pos, arg.name);
                                                            pos = writeStr(&buffer, pos, " = ");
                                                            
                                                            // Check if this argument is a File type
                                                            var is_file_arg = false;
                                                            if (inv_event) |event| {
                                                                for (event.input.fields) |field| {
                                                                    if (eql(field.name, arg.name) and field.is_file) {
                                                                        is_file_arg = true;
                                                                        break;
                                                                    }
                                                                }
                                                            }
                                                            
                                                            if (is_file_arg) {
                                                                pos = writeStr(&buffer, pos, "@embedFile(");
                                                                pos = writeStr(&buffer, pos, arg.value);
                                                                pos = writeStr(&buffer, pos, ")");
                                                            } else {
                                                                pos = writeStr(&buffer, pos, arg.value);
                                                            }
                                                        }
                                                        pos = writeStr(&buffer, pos, " });\\n");
                                                        pos = writeStr(&buffer, pos, "                    return apply(next_out);\\n");
                                                    },
                                                    else => {},
                                                }
                                            }
                                        }
                                    },
                                    else => {},
                                }
                            }
                            
                            // Then check nested continuations if no jump found yet
                            if (!has_jump) {
                                for (cont.nested) |nested| {
                                    for (nested.pipeline) |step| {
                                        switch (step) {
                                            .label_apply => |target| {
                                                if (eql(target, label)) {
                                                    has_jump = true;
                                                    // Generate the recursive call
                                                    // First call the invocation if present
                                                    for (nested.pipeline) |prev_step| {
                                                        switch (prev_step) {
                                                            .invocation => |inv| {
                                                                pos = writeStr(&buffer, pos, "                    const next_out = ");
                                                                pos = writePath(&buffer, pos, inv.path);
                                                                pos = writeStr(&buffer, pos, ".handler(.{ ");
                                                                
                                                                // Find the event declaration for File type checking
                                                                var inv_event2: ?*const EventDecl = null;
                                                                for (ast.items) |ast_item| {
                                                                    switch (ast_item) {
                                                                        .event_decl => |*event| {
                                                                            if (event.path.len == inv.path.len) {
                                                                                var matches = true;
                                                                                for (event.path, 0..) |seg, k| {
                                                                                    if (!eql(seg, inv.path[k])) {
                                                                                        matches = false;
                                                                                        break;
                                                                                    }
                                                                                }
                                                                                if (matches) {
                                                                                    inv_event2 = event;
                                                                                    break;
                                                                                }
                                                                            }
                                                                        },
                                                                        else => {},
                                                                    }
                                                                }
                                                                
                                                                for (inv.args, 0..) |arg, j| {
                                                                    if (j > 0) pos = writeStr(&buffer, pos, ", ");
                                                                    pos = writeStr(&buffer, pos, ".");
                                                                    pos = writeStr(&buffer, pos, arg.name);
                                                                    pos = writeStr(&buffer, pos, " = ");
                                                                    
                                                                    // Check if this argument is a File type
                                                                    var is_file_arg = false;
                                                                    if (inv_event2) |event| {
                                                                        for (event.input.fields) |field| {
                                                                            if (eql(field.name, arg.name) and field.is_file) {
                                                                                is_file_arg = true;
                                                                                break;
                                                                            }
                                                                        }
                                                                    }
                                                                    
                                                                    if (is_file_arg) {
                                                                        pos = writeStr(&buffer, pos, "@embedFile(");
                                                                        pos = writeStr(&buffer, pos, arg.value);
                                                                        pos = writeStr(&buffer, pos, ")");
                                                                    } else {
                                                                        pos = writeStr(&buffer, pos, arg.value);
                                                                    }
                                                                }
                                                                pos = writeStr(&buffer, pos, " });\\n");
                                                                pos = writeStr(&buffer, pos, "                    return apply(next_out);\\n");
                                                            },
                                                            else => {},
                                                        }
                                                    }
                                                }
                                            },
                                            else => {},
                                        }
                                    }
                                }
                            }
                            
                            if (!has_jump) {
                                // No jump, just empty branch
                            }
                            
                            pos = writeStr(&buffer, pos, "                },\\n");
                        }
                        
                        pos = writeStr(&buffer, pos, "            }\\n");
                        pos = writeStr(&buffer, pos, "        }\\n");
                        pos = writeStr(&buffer, pos, "    }.apply;\\n");
                    }
                    
                    // Generate flow execution
                    pos = writeStr(&buffer, pos, "    // Execute flow: ");
                    pos = writePath(&buffer, pos, item.flow.invocation.path);
                    pos = writeStr(&buffer, pos, "\\n");
                    pos = writeStr(&buffer, pos, "    const out");
                    pos = writeNum(&buffer, pos, flow_counter);  // Use actual counter!
                    pos = writeStr(&buffer, pos, " = ");
                    pos = writePath(&buffer, pos, item.flow.invocation.path);
                    pos = writeStr(&buffer, pos, ".handler(.{");
                    // Add args if any
                    if (item.flow.invocation.args.len == 0) {
                        // No args
                    } else {
                        // Find the event declaration to check field types
                        var target_event: ?*const EventDecl = null;
                        for (ast.items) |ast_item| {
                            switch (ast_item) {
                                .event_decl => |*event| {
                                    // Check if paths match
                                    if (event.path.len == item.flow.invocation.path.len) {
                                        var matches = true;
                                        for (event.path, 0..) |seg, j| {
                                            if (!eql(seg, item.flow.invocation.path[j])) {
                                                matches = false;
                                                break;
                                            }
                                        }
                                        if (matches) {
                                            target_event = event;
                                            break;
                                        }
                                    }
                                },
                                else => {},
                            }
                        }
                        
                        for (item.flow.invocation.args, 0..) |arg, i| {
                            if (i > 0) pos = writeStr(&buffer, pos, ", ");
                            pos = writeStr(&buffer, pos, ".");
                            pos = writeStr(&buffer, pos, arg.name);
                            pos = writeStr(&buffer, pos, " = ");
                            
                            // Check if this argument is a File type
                            var is_file_arg = false;
                            if (target_event) |event| {
                                for (event.input.fields) |field| {
                                    if (eql(field.name, arg.name) and field.is_file) {
                                        is_file_arg = true;
                                        break;
                                    }
                                }
                            }
                            
                            // If it's a File type, wrap with @embedFile
                            if (is_file_arg) {
                                pos = writeStr(&buffer, pos, "@embedFile(");
                                pos = writeStr(&buffer, pos, arg.value);
                                pos = writeStr(&buffer, pos, ")");
                            } else {
                                pos = writeStr(&buffer, pos, arg.value);
                            }
                        }
                    }
                    pos = writeStr(&buffer, pos, "});\\n");
                    
                    if (item.flow.post_label) |label| {
                        // Call the label function
                        pos = writeStr(&buffer, pos, "    __label_");
                        pos = writeStr(&buffer, pos, label);
                        pos = writeStr(&buffer, pos, "(out");
                        pos = writeNum(&buffer, pos, flow_counter);
                        pos = writeStr(&buffer, pos, ");\\n");
                    } else {
                        // No label, just discard result
                        pos = writeStr(&buffer, pos, "    _ = out");
                        pos = writeNum(&buffer, pos, flow_counter);
                        pos = writeStr(&buffer, pos, ";\\n");
                    }
                    flow_counter += 1;  // Increment for next flow!
                },
                else => {},
            }
        }
        
        if (has_flows) {
            pos = writeStr(&buffer, pos, "}\\n");
        } else {
            // No flows, library mode
            pos = writeStr(&buffer, pos, "\\n// Library mode - no main function needed\\n");
        }
        
        // Zero the rest
        @memset(buffer[pos..], 0);
        return buffer;
    }
    
    fn writeStr(buffer: *[MAX_SIZE]u8, pos: usize, str: []const u8) usize {
        if (pos + str.len >= MAX_SIZE) return pos;
        @memcpy(buffer[pos..pos + str.len], str);
        return pos + str.len;
    }
    
    fn writePath(buffer: *[MAX_SIZE]u8, pos: usize, path: []const []const u8) usize {
        var p = pos;
        for (path, 0..) |segment, i| {
            if (i > 0) p = writeStr(buffer, p, "_");  // Use underscore for valid Zig identifiers
            p = writeStr(buffer, p, segment);
        }
        return p;
    }
    
    fn writeNum(buffer: *[MAX_SIZE]u8, pos: usize, num: usize) usize {
        if (num == 0) return writeStr(buffer, pos, "0");
        if (num == 1) return writeStr(buffer, pos, "1");
        if (num == 2) return writeStr(buffer, pos, "2");
        if (num == 3) return writeStr(buffer, pos, "3");
        if (num == 4) return writeStr(buffer, pos, "4");
        if (num == 5) return writeStr(buffer, pos, "5");
        if (num == 6) return writeStr(buffer, pos, "6");
        if (num == 7) return writeStr(buffer, pos, "7");
        if (num == 8) return writeStr(buffer, pos, "8");
        if (num == 9) return writeStr(buffer, pos, "9");
        // For larger numbers, just use "N" for now
        return writeStr(buffer, pos, "N");
    }
    
    fn eql(a: []const u8, b: []const u8) bool {
        if (a.len != b.len) return false;
        for (a, 0..) |char, i| {
            if (char != b[i]) return false;
        }
        return true;
    }
};

// Generate code at compile-time from the AST!
const generated_code = ComptimeEmitter.emit(&PROGRAM_AST);

// The actual program entry point  
const std = @import("std");
pub fn main() void {
    // Show what was generated
    std.debug.print("Generated code:\\n", .{});
    var i: usize = 0;
    while (i < generated_code.len) : (i += 1) {
        if (generated_code[i] == 0) break;
        std.debug.print("{c}", .{generated_code[i]});
    }
    std.debug.print("\\n--- End of generated code ---\\n", .{});
}