#!/usr/bin/env node
/**
 * Koru LOC Counter
 *
 * Counts lines per language across files tracked by git. Using `git ls-files`
 * as the source of truth means we automatically skip build artifacts, scratch
 * binaries, and anything else .gitignored — no exclusion list to maintain.
 *
 * Emits one bucket per extension we explicitly care about. Tracked files of
 * other extensions (marker files, test snapshots, .txt fixtures, etc.) are
 * ignored — they would distort a "languages in this codebase" view.
 */

import { readFile } from 'fs/promises';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { spawn } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const KORU_ROOT = join(__dirname, '..');

// Extension → display name. Files with extensions outside this map are skipped.
// Languages share buckets if they should: e.g. .kz files all bucket into "Koru".
const EXTENSION_LANGUAGES = {
	kz: 'Koru',
	zig: 'Zig',
	md: 'Markdown',
	sh: 'Shell',
	js: 'JavaScript',
	py: 'Python'
};

// Files whose first lines carry one of these markers are treated as generated
// output (compiler-emitted Zig, AST dumps, etc.) and excluded — counting them
// would inflate the "handwritten code" view with mechanical transpilation
// output. We scan the first 20 lines to tolerate a few header comments before
// the generator stamp.
const GENERATED_MARKER = /\bgenerated by\b|\bauto-generated\b|\bemitted by\b|\bDO NOT EDIT\b/i;
const GENERATED_SCAN_LINES = 20;

function looksGenerated(content) {
	let scanned = 0;
	let cursor = 0;
	while (scanned < GENERATED_SCAN_LINES && cursor < content.length) {
		const nl = content.indexOf('\n', cursor);
		const end = nl === -1 ? content.length : nl;
		if (GENERATED_MARKER.test(content.slice(cursor, end))) return true;
		if (nl === -1) break;
		cursor = nl + 1;
		scanned += 1;
	}
	return false;
}

function listTrackedFiles(repoRoot) {
	return new Promise((resolve, reject) => {
		const proc = spawn('git', ['-C', repoRoot, 'ls-files', '-z'], {
			stdio: ['ignore', 'pipe', 'pipe']
		});
		let stdout = '';
		let stderr = '';
		proc.stdout.on('data', (chunk) => {
			stdout += chunk.toString('utf-8');
		});
		proc.stderr.on('data', (chunk) => {
			stderr += chunk.toString('utf-8');
		});
		proc.on('error', reject);
		proc.on('close', (code) => {
			if (code !== 0) {
				reject(new Error(`git ls-files exited ${code}: ${stderr.trim()}`));
				return;
			}
			const files = stdout.split('\0').filter(Boolean);
			resolve(files);
		});
	});
}

function extensionOf(path) {
	const slash = path.lastIndexOf('/');
	const base = slash >= 0 ? path.slice(slash + 1) : path;
	const dot = base.lastIndexOf('.');
	if (dot <= 0) return null;
	return base.slice(dot + 1).toLowerCase();
}

async function readFileStats(absPath) {
	const content = await readFile(absPath, 'utf-8');
	if (content.length === 0) return { lines: 0, generated: false };
	let nl = 0;
	for (let i = 0; i < content.length; i++) {
		if (content.charCodeAt(i) === 10) nl++;
	}
	const lines = content.endsWith('\n') ? nl : nl + 1;
	return { lines, generated: looksGenerated(content) };
}

export async function countLOC(repoRoot = KORU_ROOT) {
	const files = await listTrackedFiles(repoRoot);
	const buckets = {};
	let excludedFiles = 0;
	let excludedLines = 0;

	for (const rel of files) {
		const ext = extensionOf(rel);
		if (!ext) continue;
		const language = EXTENSION_LANGUAGES[ext];
		if (!language) continue;

		let stats;
		try {
			stats = await readFileStats(join(repoRoot, rel));
		} catch {
			// Symlinks, deleted-but-tracked, or unreadable files: skip.
			continue;
		}

		if (stats.generated) {
			excludedFiles += 1;
			excludedLines += stats.lines;
			continue;
		}

		if (!buckets[language]) buckets[language] = { files: 0, lines: 0 };
		buckets[language].files += 1;
		buckets[language].lines += stats.lines;
	}

	// The returned shape is flat by language so /status can render it directly
	// as a stacked bar. Excluded counts are not part of the snapshot payload —
	// save-snapshot.js logs them at run time for debug visibility.
	return { buckets, excludedFiles, excludedLines };
}

// Allow running as a CLI for debugging / one-off inspection.
if (import.meta.url === `file://${process.argv[1]}`) {
	countLOC()
		.then((loc) => {
			console.log(JSON.stringify(loc, null, 2));
		})
		.catch((err) => {
			console.error('count-loc failed:', err);
			process.exit(1);
		});
}
