#!/usr/bin/env bash
# Generate src/stdlib_bundle.zig — every koru_std Koru file embedded as bytes,
# keyed by a virtual absolute path (/koru_std/...). The wasm playground's
# EmbeddedFs serves these so `import "std/io"` resolves in-browser with no disk.
#
# Generated at the REPO ROOT (not src/) because Zig 0.15 forbids @embedFile from
# escaping the module's package root via "..": koru_std must sit inside it.
# Regenerate whenever koru_std changes. Idempotent; deterministic (sorted).
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=stdlib_bundle.zig
{
  echo "// GENERATED by scripts/gen-stdlib-bundle.sh — do not edit by hand."
  echo "// Every koru_std Koru file, embedded for the wasm playground's EmbeddedFs."
  echo "pub const Entry = struct { path: []const u8, bytes: []const u8 };"
  echo "pub const files = [_]Entry{"
  find koru_std \( -name '*.k' -o -name '*.kz' -o -name '*.kjs' -o -name '*.kc' -o -name '*.kgpu' \) \
    | LC_ALL=C sort \
    | while read -r f; do
        printf '    .{ .path = "/%s", .bytes = @embedFile("%s") },\n' "$f" "$f"
      done
  echo "};"
} > "$OUT"

echo "wrote $OUT ($(grep -c '@embedFile' "$OUT") files)"
