#!/usr/bin/env node

/**
 * Generate per-topic skill bundles from koru-by-example.json's `topics`.
 *
 * Each topic emits TWO artifacts from one config entry:
 *
 *   1. docs/by-example/<name>.md — the reference SHARD. Every passing
 *      positive test under the topic's clusters/includedTests, verbatim,
 *      grouped by category. Generated data; regenerated from tests; can't
 *      drift. This is the territory.
 *
 *   2. skills/<name>/SKILL.md — the routing STUB. Frontmatter `name` +
 *      `description` (which decides WHEN the skill loads into context), the
 *      authored `intro` + `rules` framing, and a pointer at the shard. Small
 *      by design — the verbatim test bodies live in the shard, not here.
 *      This is the map.
 *
 * The split is deliberate: don't inline test source into a skill (it would
 * bloat context on every trigger and drift from the suite). Don't hand-edit
 * either output — edit koru-by-example.json and regenerate.
 *
 * Topic selection mirrors the corpus:
 *   topic tests = union(passing under `clusters`) ∪ `includedTests` − `excludedTests`
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { collectPassing, resolveClusters, humanize, emitTest } from './lib/corpus.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const TESTS_DIR = path.join(ROOT, 'tests', 'regression');
const CONFIG = path.join(ROOT, 'koru-by-example.json');
const DOCS_DIR = path.join(ROOT, 'docs', 'by-example');
const SKILLS_DIR = path.join(ROOT, 'skills');

const GENERATED_MARKER =
  '<!-- GENERATED by scripts/generate-skills.js from koru-by-example.json. Do not hand-edit; edit the config and regenerate. -->';

// ----------------------------------------------------------------------
// Resolve a topic's test set, mirroring the corpus selection rules.
// ----------------------------------------------------------------------

function resolveTopicTests(topic, allTests, byName, negativeTests) {
  const clusters = topic.clusters ?? [];
  const includedTests = topic.includedTests ?? [];
  const excludedTests = new Set(topic.excludedTests ?? []);

  const { matched, unknown } = resolveClusters(allTests, clusters);
  for (const c of unknown) {
    console.warn(`[warn] topic "${topic.name}": cluster has no matching passing tests: ${c}`);
  }

  for (const name of includedTests) {
    if (byName.has(name)) {
      matched.set(name, byName.get(name));
    } else if (negativeTests.has(name)) {
      console.warn(
        `[warn] topic "${topic.name}": includedTests entry is a NEGATIVE (MUST_FAIL) test — excluded: ${name}`
      );
    } else {
      console.warn(`[warn] topic "${topic.name}": includedTests not found (or not passing): ${name}`);
    }
  }

  for (const name of excludedTests) {
    if (!matched.has(name)) {
      console.warn(`[warn] topic "${topic.name}": excludedTests entry not in topic: ${name}`);
    }
    matched.delete(name);
  }

  return [...matched.values()];
}

// ----------------------------------------------------------------------
// Group tests by full breadcrumb path; sorted keys = intended order
// (numeric directory prefixes make alphabetical = category order).
// ----------------------------------------------------------------------

function groupByBreadcrumb(tests) {
  const groups = new Map();
  for (const t of tests) {
    const key = t.breadcrumbs.join(' / ');
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key).push(t);
  }
  return groups;
}

// ----------------------------------------------------------------------
// Emit the reference shard: docs/by-example/<name>.md
// ----------------------------------------------------------------------

function buildShard(topic, tests) {
  const groups = groupByBreadcrumb(tests);
  const sortedKeys = [...groups.keys()].sort();
  const lines = [];

  lines.push(`# ${topic.title || humanize(topic.name)} — by example`);
  lines.push('');
  lines.push(GENERATED_MARKER);
  lines.push('');
  lines.push(
    `> ${tests.length} passing positive ${tests.length === 1 ? 'test' : 'tests'}, verbatim from \`tests/regression/\`. ` +
      `Generated by \`scripts/generate-skills.js\`.`
  );
  lines.push('');
  lines.push(
    'These are the receipts for the `' +
      topic.name +
      '` skill — passing tests shown as-is. The tests are the spec; when this ' +
      'doc and the compiler disagree, the test wins.'
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  // Contents
  lines.push('## Contents');
  lines.push('');
  for (const key of sortedKeys) {
    const display = key === '' ? '(uncategorized)' : key.split(' / ').map(humanize).join(' / ');
    const count = groups.get(key).length;
    lines.push(`- **${display}** — ${count} ${count === 1 ? 'test' : 'tests'}`);
  }
  lines.push('');
  lines.push('---');
  lines.push('');

  // Sections
  for (const key of sortedKeys) {
    if (key !== '') {
      lines.push(`## ${key.split(' / ').map(humanize).join(' / ')}`);
      lines.push('');
    }
    for (const t of groups.get(key)) emitTest(t, lines);
  }

  return lines.join('\n') + '\n';
}

// ----------------------------------------------------------------------
// Emit the routing skill: skills/<name>/SKILL.md
// ----------------------------------------------------------------------

function buildSkill(topic, testCount, shardRelPath) {
  const lines = [];

  // Frontmatter — name + description are the routing unit.
  lines.push('---');
  lines.push(`name: ${topic.name}`);
  lines.push(`description: ${topic.description}`);
  lines.push('---');
  lines.push('');
  lines.push(GENERATED_MARKER);
  lines.push('');
  lines.push(`# ${topic.title || humanize(topic.name)}`);
  lines.push('');

  if (topic.intro) {
    lines.push(topic.intro);
    lines.push('');
  }

  const rules = topic.rules ?? [];
  if (rules.length > 0) {
    lines.push('## What matters');
    lines.push('');
    for (const rule of rules) {
      if (typeof rule === 'string') {
        lines.push(rule);
        lines.push('');
      } else {
        lines.push(`### ${rule.title ?? '(untitled rule)'}`);
        lines.push('');
        if (rule.body) {
          lines.push(rule.body);
          lines.push('');
        }
      }
    }
  }

  // The pointer block — the verbatim examples live in the shard, not here.
  lines.push('## Worked examples');
  lines.push('');
  lines.push(
    `${testCount} passing ${testCount === 1 ? 'test' : 'tests'}, verbatim, in ` +
      `[\`${shardRelPath}\`](${shardRelPath}). The tests are the spec — read them ` +
      `as the authority on what is actually legal. This skill is the map; the shard is the territory.`
  );
  lines.push('');

  return lines.join('\n') + '\n';
}

// ----------------------------------------------------------------------
// Main
// ----------------------------------------------------------------------

const config = JSON.parse(fs.readFileSync(CONFIG, 'utf-8'));
const topics = config.topics ?? [];

if (topics.length === 0) {
  console.warn('[warn] no `topics` in koru-by-example.json — nothing to generate.');
  process.exit(0);
}

const { tests: allTests, negativeTests } = collectPassing(TESTS_DIR);
const byName = new Map(allTests.map((t) => [t.name, t]));

fs.mkdirSync(DOCS_DIR, { recursive: true });

for (const topic of topics) {
  if (!topic.name) {
    console.warn('[warn] topic with no `name` — skipped.');
    continue;
  }

  const tests = resolveTopicTests(topic, allTests, byName, negativeTests);
  if (tests.length === 0) {
    console.warn(`[warn] topic "${topic.name}" resolved to ZERO tests — shard + skill will be empty.`);
  }

  // 1. Reference shard
  const shardPath = path.join(DOCS_DIR, `${topic.name}.md`);
  fs.writeFileSync(shardPath, buildShard(topic, tests));

  // 2. Routing skill — pointer is relative to the skill file's location.
  const skillDir = path.join(SKILLS_DIR, topic.name);
  fs.mkdirSync(skillDir, { recursive: true });
  const shardRelToSkill = path.relative(skillDir, shardPath);
  fs.writeFileSync(path.join(skillDir, 'SKILL.md'), buildSkill(topic, tests.length, shardRelToSkill));

  console.log(
    `${topic.name}: ${tests.length} tests → ` +
      `${path.relative(ROOT, shardPath)} + ${path.relative(ROOT, path.join(skillDir, 'SKILL.md'))}`
  );
}
