const std = @import("std");
const ast = @import("ast");
const Parser = @import("parser").Parser;  // Needed for tests

// Define explicit error set to avoid circular inference issues
const SerializeError = error{
    OutOfMemory,
};


/// Serializes a parsed Koru AST into Zig source code containing the AST as data.
/// This is Phase 2 of the metacircular compilation architecture.
/// 
/// The output is a Zig file containing:
/// 1. Type definitions for all AST nodes
/// 2. The complete program AST as const declarations
/// 3. All Zig code preserved as string literals
pub const AstSerializer = struct {
    allocator: std.mem.Allocator,
    buffer: std.ArrayList(u8),
    indent_level: usize,

    const indent_size = 4;

    pub fn init(allocator: std.mem.Allocator) !AstSerializer {
        return AstSerializer{
            .allocator = allocator,
            .buffer = try std.ArrayList(u8).initCapacity(allocator, 4096),
            .indent_level = 0,
        };
    }

    pub fn deinit(self: *AstSerializer) void {
        self.buffer.deinit(self.allocator);
    }

    fn indent(self: *AstSerializer) void {
        self.indent_level += 1;
    }

    fn dedent(self: *AstSerializer) void {
        if (self.indent_level > 0) {
            self.indent_level -= 1;
        }
    }

    fn writeIndent(self: *AstSerializer) SerializeError!void {
        for (0..self.indent_level * indent_size) |_| {
            try self.buffer.append(self.allocator, ' ');
        }
    }

    fn write(self: *AstSerializer, text: []const u8) SerializeError!void {
        try self.buffer.appendSlice(self.allocator, text);
    }

    fn writeLine(self: *AstSerializer, text: []const u8) SerializeError!void {
        try self.writeIndent();
        try self.write(text);
        try self.write("\n");
    }

    fn writeString(self: *AstSerializer, str: []const u8) SerializeError!void {
        try self.write("\"");
        // Escape special characters in the string
        for (str) |c| {
            switch (c) {
                '\n' => try self.write("\\n"),
                '\r' => try self.write("\\r"),
                '\t' => try self.write("\\t"),
                '\\' => try self.write("\\\\"),
                '"' => try self.write("\\\""),
                else => try self.buffer.append(self.allocator, c),
            }
        }
        try self.write("\"");
    }

    fn writeMultilineString(self: *AstSerializer, str: []const u8) !void {
        // Use Zig's multiline string syntax for better readability
        try self.write("\n");
        self.indent();
        try self.writeIndent();
        try self.write("\\\\");
        
        var iter = std.mem.splitScalar(u8, str, '\n');
        var first = true;
        while (iter.next()) |line| {
            if (!first) {
                try self.write("\n");
                try self.writeIndent();
                try self.write("\\\\");
            }
            try self.write(line);
            first = false;
        }
        
        // Close the multiline string properly
        try self.write("\n");
        try self.writeIndent();
        
        self.dedent();
    }

    /// Serialize a complete Program (the root AST node)
    pub fn serialize(self: *AstSerializer, source_file: *const ast.Program) ![]const u8 {
        // Write header comment
        try self.writeLine("// Generated by Koru AST Serializer");
        try self.writeLine("// This file contains the complete program AST as Zig data structures");
        try self.writeLine("");

        // Write type definitions
        try self.writeTypeDefinitions();
        try self.writeLine("");
        
        // Define ProgramAST type alias for compiler events
        try self.writeLine("// ProgramAST is the type used by compiler events to reference the AST");
        try self.writeLine("const ProgramAST = *const Program;");
        try self.writeLine("");

        // Write the program AST
        try self.writeLine("pub const PROGRAM_AST = Program{");
        self.indent();

        // Write items array
        try self.writeLine(".items = &[_]Item{");
        self.indent();

        for (source_file.items) |item| {
            try self.serializeItem(&item);
            try self.write(",\n");
        }

        self.dedent();
        try self.writeLine("},");

        // Write module_annotations array
        try self.writeIndent();
        try self.write(".module_annotations = &[_][]const u8{");
        if (source_file.module_annotations.len > 0) {
            for (source_file.module_annotations, 0..) |annotation, i| {
                if (i > 0) try self.write(", ");
                try self.writeString(annotation);
            }
        }
        try self.write("},\n");

        // Write main_module_name
        try self.writeIndent();
        try self.write(".main_module_name = ");
        try self.writeString(source_file.main_module_name);
        try self.write(",\n");

        try self.writeLine(".allocator = undefined,");

        self.dedent();
        try self.writeLine("};");
        try self.writeLine("");

        // Generate helper function for safely deinit'ing transformed ASTs
        try self.writeLine("/// Helper to safely deinit transformed ASTs while preserving PROGRAM_AST");
        try self.writeLine("fn maybeDeinitAst(source_ast: *const Program) void {");
        self.indent();
        try self.writeLine("if (source_ast == &PROGRAM_AST) {");
        self.indent();
        try self.writeLine("// This is the const PROGRAM_AST - don't deinit");
        try self.writeLine("return;");
        self.dedent();
        try self.writeLine("}");
        try self.writeLine("// Heap-allocated transformed AST - safe to deinit");
        try self.writeLine("var mutable_ast = @constCast(source_ast);");
        try self.writeLine("mutable_ast.deinit();");
        self.dedent();
        try self.writeLine("}");

        return try self.buffer.toOwnedSlice(self.allocator);
    }

    /// Serialize a Program to JSON format
    pub fn serializeToJson(self: *AstSerializer, source_file: *const ast.Program) ![]const u8 {
        try self.write("{\n");
        self.indent();

        // Output module_annotations first
        try self.writeIndent();
        try self.write("\"module_annotations\": [\n");
        self.indent();
        for (source_file.module_annotations, 0..) |ann, i| {
            if (i > 0) {
                try self.write(",\n");
            }
            try self.writeIndent();
            try self.write("\"");
            try self.write(ann);
            try self.write("\"");
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("],\n");

        // Output items
        try self.writeIndent();
        try self.write("\"items\": [\n");
        self.indent();

        for (source_file.items, 0..) |*item, i| {
            if (i > 0) {
                try self.write(",\n");
            }
            try self.serializeItemJson(item);
        }

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("]\n");
        self.dedent();
        try self.write("}\n");

        return try self.buffer.toOwnedSlice(self.allocator);
    }

    fn writeTypeDefinitions(self: *AstSerializer) !void {
        try self.writeLine("// AST Type Definitions - imported from ast module");
        try self.writeLine("const ast = @import(\"ast\");");
        try self.writeLine("");

        // Create local aliases for all AST types used in serialization
        try self.writeLine("// Type aliases for convenience");
        try self.writeLine("const Program = ast.Program;");
        try self.writeLine("const Item = ast.Item;");
        try self.writeLine("const HostLine = ast.HostLine;");
        try self.writeLine("const EventDecl = ast.EventDecl;");
        try self.writeLine("const HostTypeDecl = ast.HostTypeDecl;");
        try self.writeLine("const ProcDecl = ast.ProcDecl;");
        try self.writeLine("const Flow = ast.Flow;");
        try self.writeLine("const EventTap = ast.EventTap;");
        try self.writeLine("const LabelDecl = ast.LabelDecl;");
        try self.writeLine("const SubflowImpl = ast.SubflowImpl;");
        try self.writeLine("const SubflowBody = ast.SubflowBody;");
        try self.writeLine("const ImportDecl = ast.ImportDecl;");
        try self.writeLine("const ModuleDecl = ast.ModuleDecl;");
        try self.writeLine("const DottedPath = ast.DottedPath;");
        try self.writeLine("const Shape = ast.Shape;");
        try self.writeLine("const Field = ast.Field;");
        try self.writeLine("const Branch = ast.Branch;");
        try self.writeLine("const BranchVariant = ast.BranchVariant;");
        try self.writeLine("const SuperShape = ast.SuperShape;");
        try self.writeLine("const Invocation = ast.Invocation;");
        try self.writeLine("const Continuation = ast.Continuation;");
        try self.writeLine("const BindingType = ast.BindingType;");
        try self.writeLine("const Step = ast.Step;");
        try self.writeLine("const Arg = ast.Arg;");
        try self.writeLine("const BranchConstructor = ast.BranchConstructor;");
        try self.writeLine("const Expression = ast.Expression;");
        try self.writeLine("const SourceLocation = ast.SourceLocation;");
        try self.writeLine("const Source = ast.Source;");
        try self.writeLine("const CapturedExpression = ast.CapturedExpression;");
        try self.writeLine("const CapturedScope = ast.CapturedScope;");
        try self.writeLine("const ScopeBinding = ast.ScopeBinding;");
    }

    fn serializeItem(self: *AstSerializer, item: *const ast.Item) !void {
        try self.writeIndent();
        switch (item.*) {
            .module_decl => |module| {
                try self.write(".{ .module_decl = ");
                try self.serializeModuleDecl(&module);
                try self.write(" }");
            },
            .host_line => |line| {
                try self.write(".{ .host_line = .{ .content = ");
                try self.writeString(line.content);
                try self.write(", .location = ");
                try self.serializeSourceLocation(&line.location);
                try self.write(", .module = ");
                try self.writeString(line.module);
                try self.write(" } }");
            },
            .event_decl => |event| {
                try self.write(".{ .event_decl = ");
                try self.serializeEventDecl(&event);
                try self.write(" }");
            },
            .proc_decl => |proc| {
                try self.write(".{ .proc_decl = ");
                try self.serializeProcDecl(&proc);
                try self.write(" }");
            },
            .flow => |flow| {
                try self.write(".{ .flow = ");
                try self.serializeFlow(&flow);
                try self.write(" }");
            },
            .import_decl => |import| {
                try self.write(".{ .import_decl = ");
                try self.serializeImportDecl(&import);
                try self.write(" }");
            },
            .subflow_impl => |subflow| {
                try self.write(".{ .subflow_impl = ");
                try self.serializeSubflowImpl(&subflow);
                try self.write(" }");
            },
            .label_decl => |label| {
                try self.write(".{ .label_decl = ");
                try self.serializeLabelDecl(&label);
                try self.write(" }");
            },
            .event_tap => |tap| {
                try self.write(".{ .event_tap = ");
                try self.serializeEventTap(&tap);
                try self.write(" }");
            },
            .host_type_decl => |host_type| {
                try self.write(".{ .host_type_decl = ");
                try self.serializeHostTypeDecl(&host_type);
                try self.write(" }");
            },
            .parse_error => |error_node| {
                // Parse errors shouldn't appear in Zig code generation
                // This is only used for --ast-json mode for IDE tooling
                try self.write(".{ .parse_error = .{ .error_code = .");
                try self.write(@tagName(error_node.error_code));
                try self.write(", .message = ");
                try self.writeString(error_node.message);
                try self.write(", .location = ");
                try self.serializeSourceLocation(&error_node.location);
                try self.write(", .raw_text = ");
                try self.writeString(error_node.raw_text);
                try self.write(", .hint = ");
                if (error_node.hint) |hint| {
                    try self.writeString(hint);
                } else {
                    try self.write("null");
                }
                try self.write(" } }");
            },

            // IR nodes (created by optimizer - should not appear in backend.zig serialization)
            // These get emitted directly by visitor_emitter.zig instead
            .native_loop => {
                // NativeLoop IR nodes should be handled by visitor_emitter, not serialized to backend.zig
                try self.write(".{ .native_loop = /* IR node - handled by emitter */ }");
            },
            .fused_event => {
                // FusedEvent IR nodes should be handled by visitor_emitter, not serialized to backend.zig
                try self.write(".{ .fused_event = /* IR node - handled by emitter */ }");
            },
            .inlined_event => {
                // InlinedEvent IR nodes should be handled by visitor_emitter, not serialized to backend.zig
                try self.write(".{ .inlined_event = /* IR node - handled by emitter */ }");
            },
            .inline_code => {
                // InlineCode IR nodes should be handled by visitor_emitter, not serialized to backend.zig
                try self.write(".{ .inline_code = /* IR node - handled by emitter */ }");
            },
        }
    }

    fn serializeModuleDecl(self: *AstSerializer, module: *const ast.ModuleDecl) SerializeError!void {
        try self.write(".{ .logical_name = ");
        try self.writeString(module.logical_name);
        try self.write(", .canonical_path = ");
        try self.writeString(module.canonical_path);
        try self.write(", .items = &[_]Item{");
        self.indent();
        for (module.items) |*item| {
            try self.writeLine("");
            try self.writeIndent();
            try self.write("            ");
            try self.serializeItem(item);
            try self.write(",");
        }
        self.dedent();
        if (module.items.len > 0) {
            try self.writeLine("");
            try self.writeIndent();
            try self.write("        ");
        }
        try self.write("}, .is_system = ");
        try self.write(if (module.is_system) "true" else "false");
        try self.write(", .annotations = &.{");
        for (module.annotations, 0..) |ann, i| {
            if (i > 0) try self.write(", ");
            try self.writeString(ann);
        }
        try self.write("}");
        try self.write(", .location = ");
        try self.serializeSourceLocation(module.location);
        try self.write(" }");
    }

    fn serializeEventDecl(self: *AstSerializer, event: *const ast.EventDecl) !void {
        try self.write("EventDecl{\n");
        self.indent();
        
        // Path
        try self.writeIndent();
        try self.write(".path = ");
        try self.serializeDottedPath(event.path);
        try self.write(",\n");
        
        // Input shape
        try self.writeIndent();
        try self.write(".input = ");
        try self.serializeShape(&event.input);
        try self.write(",\n");
        
        // Branches
        try self.writeIndent();
        try self.write(".branches = &[_]Branch{\n");
        self.indent();
        for (event.branches) |branch| {
            try self.serializeBranch(&branch);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        // Is public
        try self.writeIndent();
        try self.write(".is_public = ");
        try self.write(if (event.is_public) "true" else "false");
        try self.write(",\n");
        
        // Is implicit flow
        try self.writeIndent();
        try self.write(".is_implicit_flow = ");
        try self.write(if (event.is_implicit_flow) "true" else "false");
        try self.write(",\n");

        // Is abstract
        try self.writeIndent();
        try self.write(".is_abstract = ");
        try self.write(if (event.is_abstract) "true" else "false");
        try self.write(",\n");

        // Annotations
        try self.writeIndent();
        try self.write(".annotations = &.{\n");
        self.indent();
        for (event.annotations) |ann| {
            try self.writeIndent();
            try self.writeString(ann);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        // Location
        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(&event.location);
        try self.write(",\n");

        // Module
        try self.writeIndent();
        try self.write(".module = ");
        try self.writeString(event.module);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeProcDecl(self: *AstSerializer, proc: *const ast.ProcDecl) !void {
        try self.write("ProcDecl{\n");
        self.indent();
        
        // Path
        try self.writeIndent();
        try self.write(".path = ");
        try self.serializeDottedPath(proc.path);
        try self.write(",\n");
        
        // Body (Zig code as multiline string)
        try self.writeIndent();
        try self.write(".body = ");
        
        if (std.mem.indexOf(u8, proc.body, "\n") != null) {
            try self.writeMultilineString(proc.body);
            try self.write(",\n");
        } else {
            try self.writeString(proc.body);
            try self.write(",\n");
        }
        
        // Serialize inline flows
        try self.writeIndent();
        try self.write(".inline_flows = &[_]Flow{\n");
        self.indent();
        for (proc.inline_flows) |*flow| {
            try self.serializeFlow(flow);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");
        
        // Serialize annotations
        try self.writeIndent();
        try self.write(".annotations = &.{\n");
        self.indent();
        for (proc.annotations) |ann| {
            try self.writeIndent();
            try self.writeString(ann);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        // Serialize target
        try self.writeIndent();
        if (proc.target) |target| {
            try self.write(".target = ");
            try self.writeString(target);
            try self.write(",\n");
        } else {
            try self.write(".target = null,\n");
        }

        // Serialize is_impl flag
        try self.writeIndent();
        try self.write(".is_impl = ");
        try self.write(if (proc.is_impl) "true" else "false");
        try self.write(",\n");

        // Purity tracking
        try self.writeIndent();
        try self.write(".is_pure = ");
        try self.write(if (proc.is_pure) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".is_transitively_pure = ");
        try self.write(if (proc.is_transitively_pure) "true" else "false");
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(&proc.location);
        try self.write(",\n");

        // Module
        try self.writeIndent();
        try self.write(".module = ");
        try self.writeString(proc.module);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeFlow(self: *AstSerializer, flow: *const ast.Flow) SerializeError!void {
        try self.write("Flow{\n");
        self.indent();
        
        // Invocation
        try self.writeIndent();
        try self.write(".invocation = ");
        try self.serializeInvocation(&flow.invocation);
        try self.write(",\n");
        
        // Continuations
        try self.writeIndent();
        try self.write(".continuations = &[_]Continuation{\n");
        self.indent();
        for (flow.continuations) |cont| {
            try self.serializeContinuation(&cont);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");
        
        // Pre-label (always write, even if null)
        try self.writeIndent();
        try self.write(".pre_label = ");
        if (flow.pre_label) |label| {
            try self.writeString(label);
        } else {
            try self.write("null");
        }
        try self.write(",\n");
        
        // Post-label (always write, even if null)
        try self.writeIndent();
        try self.write(".post_label = ");
        if (flow.post_label) |label| {
            try self.writeString(label);
        } else {
            try self.write("null");
        }
        try self.write(",\n");
        
        // SuperShape for inline flows with union types
        try self.writeIndent();
        try self.write(".super_shape = ");
        if (flow.super_shape) |ss| {
            try self.serializeSuperShape(&ss);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        // Purity tracking
        try self.writeIndent();
        try self.write(".is_pure = ");
        try self.write(if (flow.is_pure) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".is_transitively_pure = ");
        try self.write(if (flow.is_transitively_pure) "true" else "false");
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(&flow.location);
        try self.write(",\n");

        // Module
        try self.writeIndent();
        try self.write(".module = ");
        try self.writeString(flow.module);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeSuperShape(self: *AstSerializer, ss: *const ast.SuperShape) SerializeError!void {
        try self.write("SuperShape{ .branches = &[_]SuperShape.BranchVariant{\n");
        self.indent();

        for (ss.branches) |branch| {
            try self.writeIndent();
            try self.write("SuperShape.BranchVariant{\n");
            self.indent();
            
            try self.writeIndent();
            try self.write(".name = ");
            try self.writeString(branch.name);
            try self.write(",\n");
            
            try self.writeIndent();
            try self.write(".payload = ");
            try self.serializeShape(&branch.payload);
            try self.write(",\n");
            
            try self.writeIndent();
            try self.write(".sources = &[_]DottedPath{\n");
            self.indent();
            for (branch.sources) |source| {
                try self.writeIndent();
                try self.serializeDottedPath(source);
                try self.write(",\n");
            }
            self.dedent();
            try self.writeIndent();
            try self.write("},\n");

            self.dedent();
            try self.writeIndent();
            try self.write("},\n");
        }

        self.dedent();
        try self.writeIndent();
        try self.write("} }");
    }

    fn serializeEventTap(self: *AstSerializer, tap: *const ast.EventTap) SerializeError!void {
        try self.write("EventTap{\n");
        self.indent();
        
        // Source (nullable)
        try self.writeIndent();
        try self.write(".source = ");
        if (tap.source) |source| {
            try self.serializeDottedPath(source);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        // Destination (nullable)
        try self.writeIndent();
        try self.write(".destination = ");
        if (tap.destination) |dest| {
            try self.serializeDottedPath(dest);
        } else {
            try self.write("null");
        }
        try self.write(",\n");
        
        // Continuations
        try self.writeIndent();
        try self.write(".continuations = &[_]Continuation{\n");
        self.indent();
        for (tap.continuations) |cont| {
            try self.serializeContinuation(&cont);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");
        
        // is_input_tap
        try self.writeIndent();
        try self.write(".is_input_tap = ");
        if (tap.is_input_tap) {
            try self.write("true");
        } else {
            try self.write("false");
        }
        try self.write(",\n");

        // Annotations
        try self.writeIndent();
        try self.write(".annotations = &.{\n");
        self.indent();
        for (tap.annotations) |ann| {
            try self.writeIndent();
            try self.writeString(ann);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(tap.location);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".module = ");
        try self.writeString(tap.module);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeHostTypeDecl(self: *AstSerializer, host_type: *const ast.HostTypeDecl) SerializeError!void {
        try self.write("HostTypeDecl{\n");
        self.indent();

        // Name
        try self.writeIndent();
        try self.write(".name = ");
        try self.writeString(host_type.name);
        try self.write(",\n");

        // Shape
        try self.writeIndent();
        try self.write(".shape = ");
        try self.serializeShape(&host_type.shape);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeInvocation(self: *AstSerializer, invoc: *const ast.Invocation) SerializeError!void {
        try self.write("Invocation{\n");
        self.indent();

        // Path
        try self.writeIndent();
        try self.write(".path = ");
        try self.serializeDottedPath(invoc.path);
        try self.write(",\n");

        // Args
        try self.writeIndent();
        try self.write(".args = &[_]Arg{\n");
        self.indent();
        for (invoc.args) |arg| {
            try self.serializeArg(&arg);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        // inserted_by_tap flag (CRITICAL for tap transformation)
        try self.writeIndent();
        try self.write(".inserted_by_tap = ");
        try self.write(if (invoc.inserted_by_tap) "true" else "false");
        try self.write(",\n");

        // from_opaque_tap flag (CRITICAL for preventing infinite recursion!)
        try self.writeIndent();
        try self.write(".from_opaque_tap = ");
        try self.write(if (invoc.from_opaque_tap) "true" else "false");
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeArg(self: *AstSerializer, arg: *const ast.Arg) SerializeError!void {
        try self.writeIndent();
        try self.write("Arg{ .name = ");
        try self.writeString(arg.name);
        try self.write(", .value = ");
        try self.writeString(arg.value);
        try self.write(", .source_value = ");
        if (arg.source_value) |source| {
            try self.write("&");
            try self.serializeSource(source);
        } else {
            try self.write("null");
        }
        try self.write(", .expression_value = ");
        if (arg.expression_value) |expr| {
            try self.write("&");
            try self.serializeCapturedExpression(expr);
        } else {
            try self.write("null");
        }
        try self.write(" }");
    }

    fn serializeSource(self: *AstSerializer, source: *const ast.Source) SerializeError!void {
        try self.write("Source{\n");
        self.indent();

        // Text
        try self.writeIndent();
        try self.write(".text = ");
        if (std.mem.indexOf(u8, source.text, "\n") != null) {
            try self.writeMultilineString(source.text);
        } else {
            try self.writeString(source.text);
        }
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(&source.location);
        try self.write(",\n");

        // Scope
        try self.writeIndent();
        try self.write(".scope = ");
        try self.serializeCapturedScope(&source.scope);
        try self.write(",\n");

        // Phantom type
        try self.writeIndent();
        try self.write(".phantom_type = ");
        if (source.phantom_type) |pt| {
            try self.writeString(pt);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeCapturedExpression(self: *AstSerializer, expr: *const ast.CapturedExpression) SerializeError!void {
        try self.write("CapturedExpression{\n");
        self.indent();

        // Text
        try self.writeIndent();
        try self.write(".text = ");
        try self.writeString(expr.text);
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(&expr.location);
        try self.write(",\n");

        // Scope
        try self.writeIndent();
        try self.write(".scope = ");
        try self.serializeCapturedScope(&expr.scope);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeCapturedScope(self: *AstSerializer, scope: *const ast.CapturedScope) SerializeError!void {
        try self.write("CapturedScope{\n");
        self.indent();

        try self.writeIndent();
        try self.write(".bindings = &[_]ScopeBinding{\n");
        self.indent();
        for (scope.bindings) |*binding| {
            try self.serializeScopeBinding(binding);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeScopeBinding(self: *AstSerializer, binding: *const ast.ScopeBinding) SerializeError!void {
        try self.writeIndent();
        try self.write("ScopeBinding{\n");
        self.indent();

        try self.writeIndent();
        try self.write(".name = ");
        try self.writeString(binding.name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".type = ");
        try self.writeString(binding.type);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".value_ref = ");
        try self.writeString(binding.value_ref);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeContinuation(self: *AstSerializer, cont: *const ast.Continuation) SerializeError!void {
        try self.writeIndent();
        try self.write("Continuation{\n");
        self.indent();
        
        // Branch name
        try self.writeIndent();
        try self.write(".branch = ");
        try self.writeString(cont.branch);
        try self.write(",\n");
        
        // Binding (always write, even if null)
        try self.writeIndent();
        try self.write(".binding = ");
        if (cont.binding) |bind| {
            try self.writeString(bind);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        // Binding type
        try self.writeIndent();
        try self.write(".binding_type = .");
        try self.write(@tagName(cont.binding_type));
        try self.write(",\n");

        // Binding annotations (e.g., [mutable])
        try self.writeIndent();
        try self.write(".binding_annotations = &[_][]const u8{");
        if (cont.binding_annotations.len > 0) {
            try self.write("\n");
            self.indent();
            for (cont.binding_annotations) |ann| {
                try self.writeIndent();
                try self.writeString(ann);
                try self.write(",\n");
            }
            self.dedent();
            try self.writeIndent();
        }
        try self.write("},\n");

        // Catch-all flag
        try self.writeIndent();
        try self.write(".is_catchall = ");
        try self.write(if (cont.is_catchall) "true" else "false");
        try self.write(",\n");

        // Catch-all metatype
        try self.writeIndent();
        try self.write(".catchall_metatype = ");
        if (cont.catchall_metatype) |meta| {
            try self.writeString(meta);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        // Condition (where clause)
        try self.writeIndent();
        try self.write(".condition = ");
        if (cont.condition) |cond| {
            try self.writeString(cond);
        } else {
            try self.write("null");
        }
        try self.write(",\n");
        
        // Condition expression (parsed where clause - for now just null)
        try self.writeIndent();
        try self.write(".condition_expr = null,\n");
        
        // Node
        try self.writeIndent();
        if (cont.node) |step| {
            try self.write(".node = ");
            try self.serializeStep(&step);
            try self.write(",\n");
        } else {
            try self.write(".node = null,\n");
        }

        // Indent
        try self.writeIndent();
        try self.write(".indent = ");
        const indent_str = try std.fmt.allocPrint(self.allocator, "{}", .{cont.indent});
        defer self.allocator.free(indent_str);
        try self.write(indent_str);
        try self.write(",\n");

        // Continuations
        try self.writeIndent();
        try self.write(".continuations = &[_]Continuation{\n");
        self.indent();
        for (cont.continuations) |nested| {
            try self.serializeContinuation(&nested);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        // Location
        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(&cont.location);
        try self.write(",\n");
        
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeStep(self: *AstSerializer, step: *const ast.Step) SerializeError!void {
        try self.writeIndent();
        switch (step.*) {
            .invocation => |invoc| {
                try self.write(".{ .invocation = ");
                try self.serializeInvocation(&invoc);
                try self.write(" }");
            },
            .label_apply => |label| {
                try self.write(".{ .label_apply = ");
                try self.writeString(label);
                try self.write(" }");
            },
            .label_with_invocation => |li| {
                try self.write(".{ .label_with_invocation = .{ .label = ");
                try self.writeString(li.label);
                try self.write(", .invocation = ");
                try self.serializeInvocation(&li.invocation);
                try self.write(", .is_declaration = ");
                if (li.is_declaration) {
                    try self.write("true");
                } else {
                    try self.write("false");
                }
                try self.write(" } }");
            },
            .label_jump => |lj| {
                try self.write(".{ .label_jump = .{ .label = ");
                try self.writeString(lj.label);
                try self.write(", .args = &[_]Arg{");
                for (lj.args, 0..) |arg, i| {
                    if (i > 0) try self.write(", ");
                    try self.write(".{ .name = ");
                    try self.writeString(arg.name);
                    try self.write(", .value = ");
                    try self.writeString(arg.value);
                    try self.write(" }");
                }
                try self.write("} } }");
            },
            .terminal => {
                try self.write(".{ .terminal = {} }");
            },
            .conditional_block => |cb| {
                try self.write(".{ .conditional_block = .{ .condition = ");
                if (cb.condition) |cond| {
                    try self.writeString(cond);
                } else {
                    try self.write("null");
                }
                try self.write(", .condition_expr = null, .nodes = &[_]Node{\n");
                self.indent();
                for (cb.nodes) |inner_step| {
                    try self.serializeStep(&inner_step);
                    try self.write(",\n");
                }
                self.dedent();
                try self.writeIndent();
                try self.write("}, .inserted_by_tap = ");
                try self.write(if (cb.inserted_by_tap) "true" else "false");
                try self.write(", .from_opaque_tap = ");
                try self.write(if (cb.from_opaque_tap) "true" else "false");
                try self.write(" } }");
            },
            .deref => |d| {
                try self.write(".{ .deref = .{ .target = ");
                try self.writeString(d.target);
                if (d.args) |args| {
                    try self.write(", .args = &[_]Arg{\n");
                    self.indent();
                    for (args) |arg| {
                        try self.serializeArg(&arg);
                        try self.write(",\n");
                    }
                    self.dedent();
                    try self.writeIndent();
                    try self.write("}");
                } else {
                    try self.write(", .args = null");
                }
                try self.write(" } }");
            },
            .branch_constructor => |bc| {
                try self.write(".{ .branch_constructor = ");
                try self.serializeBranchConstructor(&bc);
                try self.write(" }");
            },
            .metatype_binding => |mb| {
                try self.write(".{ .metatype_binding = .{ .metatype = ");
                try self.writeString(mb.metatype);
                try self.write(", .binding = ");
                try self.writeString(mb.binding);
                try self.write(", .source_event = ");
                try self.writeString(mb.source_event);
                try self.write(", .dest_event = ");
                if (mb.dest_event) |dest| {
                    try self.writeString(dest);
                } else {
                    try self.write("null");
                }
                try self.write(", .branch = ");
                try self.writeString(mb.branch);
                try self.write(", .inserted_by_tap = ");
                try self.write(if (mb.inserted_by_tap) "true" else "false");
                try self.write(", .from_opaque_tap = ");
                try self.write(if (mb.from_opaque_tap) "true" else "false");
                try self.write(" } }");
            },
            .inline_code => |code| {
                try self.write(".{ .inline_code = ");
                try self.writeString(code);
                try self.write(" }");
            },
            .foreach => |fe| {
                try self.write(".{ .foreach = .{ .iterable = ");
                try self.writeString(fe.iterable);
                try self.write(", .element_type = ");
                if (fe.element_type) |et| {
                    try self.writeString(et);
                } else {
                    try self.write("null");
                }
                try self.write(", .branches = &[_]NamedBranch{} } }");  // TODO: serialize branches
            },
            .conditional => |cond| {
                try self.write(".{ .conditional = .{ .condition = ");
                try self.writeString(cond.condition);
                try self.write(", .condition_expr = null, .branches = &[_]NamedBranch{} } }");  // TODO: serialize branches
            },
            .capture => |cap| {
                try self.write(".{ .capture = .{ .init_expr = ");
                try self.writeString(cap.init_expr);
                try self.write(", .branches = &[_]NamedBranch{} } }");  // TODO: serialize branches
            },
            .assignment => |asgn| {
                try self.write(".{ .assignment = .{ .target = ");
                try self.writeString(asgn.target);
                try self.write(", .fields = &[_]Field{} } }");  // TODO: serialize fields
            },
        }
    }

    fn serializeBranchConstructor(self: *AstSerializer, bc: *const ast.BranchConstructor) SerializeError!void {
        try self.write("BranchConstructor{\n");
        self.indent();
        
        try self.writeIndent();
        try self.write(".branch_name = ");
        try self.writeString(bc.branch_name);
        try self.write(",\n");
        
        try self.writeIndent();
        try self.write(".fields = &[_]Field{\n");
        self.indent();
        for (bc.fields) |field| {
            try self.serializeField(&field);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");
        
        try self.writeIndent();
        try self.write(".has_expressions = ");
        try self.write(if (bc.has_expressions) "true" else "false");
        try self.write(",\n");
        
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeImportDecl(self: *AstSerializer, import: *const ast.ImportDecl) !void {
        try self.write("ImportDecl{ .path = ");
        try self.writeString(import.path);
        try self.write(", .local_name = ");
        if (import.local_name) |name| {
            try self.writeString(name);
        } else {
            try self.write("null");
        }
        try self.write(", .location = .{ .file = ");
        try self.writeString(import.location.file);
        try self.buffer.writer(self.allocator).print(", .line = {d}, .column = {d} }}, .module = ", .{import.location.line, import.location.column});
        try self.writeString(import.module);
        try self.write(" }");
    }

    fn serializeSubflowImpl(self: *AstSerializer, subflow: *const ast.SubflowImpl) !void {
        try self.write("SubflowImpl{\n");
        self.indent();

        try self.writeIndent();
        try self.write(".event_path = ");
        try self.serializeDottedPath(subflow.event_path);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".body = ");
        switch (subflow.body) {
            .flow => |flow| {
                try self.write(".{ .flow = ");
                try self.serializeFlow(&flow);
                try self.write(" }");
            },
            .immediate => |imm| {
                try self.write(".{ .immediate = ");
                try self.serializeBranchConstructor(&imm);
                try self.write(" }");
            },
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".is_impl = ");
        try self.write(if (subflow.is_impl) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".location = ");
        try self.serializeSourceLocation(subflow.location);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".module = ");
        try self.writeString(subflow.module);
        try self.write(",\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeLabelDecl(self: *AstSerializer, label: *const ast.LabelDecl) !void {
        try self.write("LabelDecl{\n");
        self.indent();

        try self.writeIndent();
        try self.write(".name = ");
        try self.writeString(label.name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".continuations = &[_]Continuation{\n");
        self.indent();
        for (label.continuations) |cont| {
            try self.serializeContinuation(&cont);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("},\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeBranch(self: *AstSerializer, branch: *const ast.Branch) !void {
        try self.writeIndent();
        try self.write("Branch{\n");
        self.indent();

        try self.writeIndent();
        try self.write(".name = ");
        try self.writeString(branch.name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".payload = ");
        try self.serializeShape(&branch.payload);
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".is_deferred = ");
        try self.write(if (branch.is_deferred) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".is_optional = ");
        try self.write(if (branch.is_optional) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write(".annotations = &.{");
        for (branch.annotations, 0..) |ann, i| {
            if (i > 0) try self.write(", ");
            try self.writeString(ann);
        }
        try self.write("},\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeShape(self: *AstSerializer, shape: *const ast.Shape) !void {
        try self.write("Shape{ .fields = &[_]Field{\n");
        self.indent();
        for (shape.fields) |field| {
            try self.serializeField(&field);
            try self.write(",\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("} }");
    }

    fn serializeField(self: *AstSerializer, field: *const ast.Field) !void {
        try self.writeIndent();
        try self.write("Field{ .name = ");
        try self.writeString(field.name);
        try self.write(", .type = ");
        try self.writeString(field.type);

        // Serialize module_path for cross-module types
        try self.write(", .module_path = ");
        if (field.module_path) |module_path| {
            try self.writeString(module_path);
        } else {
            try self.write("null");
        }

        try self.write(", .is_source = ");
        try self.write(if (field.is_source) "true" else "false");
        try self.write(", .is_file = ");
        try self.write(if (field.is_file) "true" else "false");
        try self.write(", .is_embed_file = ");
        try self.write(if (field.is_embed_file) "true" else "false");
        try self.write(", .is_expression = ");
        try self.write(if (field.is_expression) "true" else "false");

        // Serialize phantom state (now just an opaque string)
        try self.write(", .phantom = ");
        if (field.phantom) |phantom| {
            try self.writeString(phantom);
        } else {
            try self.write("null");
        }
        
        // Serialize expression fields for branch constructors
        try self.write(", .expression = ");
        if (field.expression) |expr| {
            try self.write("&");
            try self.serializeExpression(expr);
        } else {
            try self.write("null");
        }
        
        try self.write(", .expression_str = ");
        if (field.expression_str) |expr_str| {
            try self.writeString(expr_str);
        } else {
            try self.write("null");
        }
        
        try self.write(", .owns_expression = ");
        try self.write(if (field.owns_expression) "true" else "false");
        
        try self.write(" }");
    }

    fn serializeExpression(self: *AstSerializer, expr: *const ast.Expression) SerializeError!void {
        try self.write("Expression{ .node = ");
        try self.serializeExprNode(&expr.node);
        try self.write(" }");
    }
    
    fn serializeExprNode(self: *AstSerializer, node: *const ast.ExprNode) SerializeError!void {
        switch (node.*) {
            .literal => |lit| {
                try self.write(".{ .literal = ");
                switch (lit) {
                    .number => |n| {
                        try self.write(".{ .number = ");
                        try self.writeString(n);
                        try self.write(" }");
                    },
                    .string => |s| {
                        try self.write(".{ .string = ");
                        try self.writeString(s);
                        try self.write(" }");
                    },
                    .boolean => |b| {
                        try self.write(".{ .boolean = ");
                        try self.write(if (b) "true" else "false");
                        try self.write(" }");
                    },
                }
                try self.write(" }");
            },
            .identifier => |id| {
                try self.write(".{ .identifier = ");
                try self.writeString(id);
                try self.write(" }");
            },
            .binary => |bin| {
                try self.write(".{ .binary = BinaryOp{ .op = .");
                try self.write(@tagName(bin.op));
                try self.write(", .left = &");
                try self.serializeExpression(bin.left);
                try self.write(", .right = &");
                try self.serializeExpression(bin.right);
                try self.write(" } }");
            },
            .unary => |un| {
                try self.write(".{ .unary = UnaryOp{ .op = .");
                try self.write(@tagName(un.op));
                try self.write(", .operand = &");
                try self.serializeExpression(un.operand);
                try self.write(" } }");
            },
            .field_access => |fa| {
                try self.write(".{ .field_access = FieldAccess{ .object = &");
                try self.serializeExpression(fa.object);
                try self.write(", .field = ");
                try self.writeString(fa.field);
                try self.write(" } }");
            },
            .grouped => |g| {
                try self.write(".{ .grouped = &");
                try self.serializeExpression(g);
                try self.write(" }");
            },
        }
    }
    
    fn serializePath(self: *AstSerializer, segments: []const []const u8) !void {
        try self.write("&[_][]const u8{");
        for (segments, 0..) |seg, i| {
            if (i > 0) try self.write(", ");
            try self.writeString(seg);
        }
        try self.write("}");
    }

    /// Serialize a DottedPath struct with module_qualifier and segments
    fn serializeDottedPath(self: *AstSerializer, path: ast.DottedPath) !void {
        try self.write(".{ .module_qualifier = ");

        // Write module qualifier (nullable)
        if (path.module_qualifier) |mq| {
            try self.writeString(mq);
        } else {
            try self.write("null");
        }

        try self.write(", .segments = &[_][]const u8{");

        // Write segments
        for (path.segments, 0..) |seg, i| {
            if (i > 0) try self.write(", ");
            try self.writeString(seg);
        }

        try self.write("} }");
    }

    fn serializeSourceLocation(self: *AstSerializer, location: anytype) !void {
        try self.write(".{ .line = ");
        const line_str = try std.fmt.allocPrint(self.allocator, "{d}", .{location.line});
        defer self.allocator.free(line_str);
        try self.write(line_str);
        try self.write(", .column = ");
        const col_str = try std.fmt.allocPrint(self.allocator, "{d}", .{location.column});
        defer self.allocator.free(col_str);
        try self.write(col_str);
        try self.write(", .file = ");
        try self.writeString(location.file);
        try self.write(" }");
    }

    // JSON Serialization Methods

    fn serializeItemJson(self: *AstSerializer, item: *const ast.Item) !void {
        try self.writeIndent();
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"type\": ");

        switch (item.*) {
            .event_decl => {
                try self.writeString("event_decl");
                try self.write(",\n");
                try self.serializeEventDeclJson(&item.event_decl);
            },
            .proc_decl => {
                try self.writeString("proc_decl");
                try self.write(",\n");
                try self.serializeProcDeclJson(&item.proc_decl);
            },
            .flow => {
                try self.writeString("flow");
                try self.write(",\n");
                try self.serializeFlowJson(&item.flow);
            },
            .import_decl => {
                try self.writeString("import_decl");
                try self.write(",\n");
                try self.serializeImportDeclJson(&item.import_decl);
            },
            .module_decl => {
                try self.writeString("module_decl");
                try self.write(",\n");
                try self.serializeModuleDeclJson(&item.module_decl);
            },
            .host_line => {
                try self.writeString("host_line");
                try self.write(",\n");
                try self.serializeHostLineJson(&item.host_line);
            },
            .event_tap => {
                try self.writeString("event_tap");
                try self.write(",\n");
                try self.serializeEventTapJson(&item.event_tap);
            },
            .label_decl => {
                try self.writeString("label_decl");
                try self.write(",\n");
                try self.serializeLabelDeclJson(&item.label_decl);
            },
            .subflow_impl => {
                try self.writeString("subflow_impl");
                try self.write(",\n");
                try self.serializeSubflowImplJson(&item.subflow_impl);
            },
            .host_type_decl => {
                try self.writeString("host_type_decl");
                try self.write(",\n");
                try self.serializeHostTypeDeclJson(&item.host_type_decl);
            },
            .parse_error => {
                try self.writeString("parse_error");
                try self.write(",\n");
                try self.serializeParseErrorNodeJson(&item.parse_error);
            },

            // IR nodes (created by optimizer)
            .native_loop => {
                try self.writeString("native_loop");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"note\": \"IR node - emitted directly by visitor_emitter\"");
            },
            .fused_event => {
                try self.writeString("fused_event");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"note\": \"IR node - emitted directly by visitor_emitter\"");
            },
            .inlined_event => {
                try self.writeString("inlined_event");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"note\": \"IR node - emitted directly by visitor_emitter\"");
            },
            .inline_code => {
                try self.writeString("inline_code");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"note\": \"IR node - template-generated inline code\"");
            },
        }

        self.dedent();
        try self.write("\n");
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeEventDeclJson(self: *AstSerializer, event: *const ast.EventDecl) !void {
        // Event name
        try self.writeIndent();
        try self.write("\"name\": ");
        if (event.path.segments.len > 0) {
            try self.writeString(event.path.segments[event.path.segments.len - 1]);
        } else {
            try self.writeString("");
        }
        try self.write(",\n");

        // Path
        try self.writeIndent();
        try self.write("\"path\": ");
        try self.serializeDottedPathJson(&event.path);
        try self.write(",\n");

        // Module
        try self.writeIndent();
        try self.write("\"module\": ");
        try self.writeString(event.module);
        try self.write(",\n");

        // Input shape
        try self.writeIndent();
        try self.write("\"input\": ");
        try self.serializeShapeJson(&event.input);
        try self.write(",\n");

        // Branches
        try self.writeIndent();
        try self.write("\"branches\": [\n");
        self.indent();
        for (event.branches, 0..) |*branch, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeBranchJson(branch);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("],\n");

        // Location
        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&event.location);
    }

    fn serializeProcDeclJson(self: *AstSerializer, proc: *const ast.ProcDecl) !void {
        try self.writeIndent();
        try self.write("\"event_name\": ");
        if (proc.path.segments.len > 0) {
            try self.writeString(proc.path.segments[proc.path.segments.len - 1]);
        } else {
            try self.writeString("");
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"path\": ");
        try self.serializeDottedPathJson(&proc.path);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"module\": ");
        try self.writeString(proc.module);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"target\": ");
        if (proc.target) |t| {
            try self.writeString(t);
        } else {
            try self.writeString("zig");
        }
        try self.write(",\n");

        // Inline flows
        try self.writeIndent();
        try self.write("\"inline_flows\": [\n");
        self.indent();
        for (proc.inline_flows, 0..) |*flow, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeFlowDetailJson(flow);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("],\n");

        try self.writeIndent();
        try self.write("\"is_pure\": ");
        try self.write(if (proc.is_pure) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&proc.location);
    }

    fn serializeFlowJson(self: *AstSerializer, flow: *const ast.Flow) !void {
        // Invocation
        try self.writeIndent();
        try self.write("\"invocation\": ");
        try self.serializeInvocationJson(&flow.invocation);
        try self.write(",\n");

        // Continuations
        try self.writeIndent();
        try self.write("\"continuations\": [\n");
        self.indent();
        for (flow.continuations, 0..) |*cont, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeContinuationJson(cont);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("],\n");

        // Labels
        try self.writeIndent();
        try self.write("\"pre_label\": ");
        if (flow.pre_label) |label| {
            try self.writeString(label);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"post_label\": ");
        if (flow.post_label) |label| {
            try self.writeString(label);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&flow.location);
    }

    fn serializeFlowDetailJson(self: *AstSerializer, flow: *const ast.Flow) !void {
        try self.writeIndent();
        try self.write("{\n");
        self.indent();

        // Invocation
        try self.writeIndent();
        try self.write("\"invocation\": ");
        try self.serializeInvocationJson(&flow.invocation);
        try self.write(",\n");

        // Continuations
        try self.writeIndent();
        try self.write("\"continuations\": [\n");
        self.indent();
        for (flow.continuations, 0..) |*cont, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeContinuationJson(cont);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("],\n");

        // Labels
        try self.writeIndent();
        try self.write("\"pre_label\": ");
        if (flow.pre_label) |label| {
            try self.writeString(label);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"post_label\": ");
        if (flow.post_label) |label| {
            try self.writeString(label);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&flow.location);

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeInvocationJson(self: *AstSerializer, inv: *const ast.Invocation) !void {
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"event\": ");
        try self.serializeDottedPathJson(&inv.path);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"args\": [\n");
        self.indent();
        for (inv.args, 0..) |*arg, i| {
            if (i > 0) try self.write(",\n");
            try self.writeIndent();
            try self.write("{\n");
            self.indent();
            try self.writeIndent();
            try self.write("\"name\": ");
            try self.writeString(arg.name);
            try self.write(",\n");
            try self.writeIndent();
            try self.write("\"value\": ");
            try self.writeString(arg.value);
            if (arg.source_value) |source| {
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"source_value\": ");
                try self.serializeSourceJson(source);
            }
            if (arg.expression_value) |expr| {
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"expression_value\": ");
                try self.serializeCapturedExpressionJson(expr);
            }
            try self.write("\n");
            self.dedent();
            try self.writeIndent();
            try self.write("}");
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("]\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeContinuationJson(self: *AstSerializer, cont: *const ast.Continuation) SerializeError!void {
        try self.writeIndent();
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"branch\": ");
        try self.writeString(cont.branch);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"binding\": ");
        if (cont.binding) |b| {
            try self.writeString(b);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"binding_type\": ");
        try self.writeString(switch (cont.binding_type) {
            .branch_payload => "branch_payload",
            .transition => "transition",
        });
        try self.write(",\n");

        // Step (optional)
        try self.writeIndent();
        if (cont.node) |*step| {
            try self.write("\"step\": ");
            try self.serializeStepJson(step);
            try self.write(",\n");
        } else {
            try self.write("\"step\": null,\n");
        }

        // Continuations
        try self.writeIndent();
        try self.write("\"continuations\": [\n");
        self.indent();
        for (cont.continuations, 0..) |*nested, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeContinuationJson(nested);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("]\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeNamedBranchJson(self: *AstSerializer, branch: *const ast.NamedBranch) SerializeError!void {
        try self.writeIndent();
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"name\": ");
        try self.writeString(branch.name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"binding\": ");
        if (branch.binding) |b| {
            try self.writeString(b);
        } else {
            try self.write("null");
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"body\": [\n");
        self.indent();
        for (branch.body, 0..) |*cont, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeContinuationJson(cont);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("]\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeStepJson(self: *AstSerializer, step: *const ast.Step) SerializeError!void {
        try self.writeIndent();
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"type\": ");

        switch (step.*) {
            .invocation => |*inv| {
                try self.writeString("invocation");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"invocation\": ");
                try self.serializeInvocationJson(inv);
            },
            .branch_constructor => |*bc| {
                try self.writeString("branch_constructor");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"branch_constructor\": ");
                try self.serializeBranchConstructorJson(bc);
            },
            .label_apply => |label| {
                try self.writeString("label_apply");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"label\": ");
                try self.writeString(label);
            },
            .label_with_invocation => |*lwi| {
                try self.writeString("label_with_invocation");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"label\": ");
                try self.writeString(lwi.label);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"invocation\": ");
                try self.serializeInvocationJson(&lwi.invocation);
            },
            .label_jump => |*lj| {
                try self.writeString("label_jump");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"label\": ");
                try self.writeString(lj.label);
            },
            .terminal => {
                try self.writeString("terminal");
            },
            .conditional_block => |*cb| {
                try self.writeString("conditional_block");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"condition\": ");
                if (cb.condition) |cond| {
                    try self.writeString(cond);
                } else {
                    try self.write("null");
                }
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"steps\": [\n");
                self.indent();
                for (cb.nodes, 0..) |*inner_step, i| {
                    if (i > 0) try self.write(",\n");
                    try self.serializeStepJson(inner_step);
                }
                try self.write("\n");
                self.dedent();
                try self.writeIndent();
                try self.write("]");
            },
            .deref => |*d| {
                try self.writeString("deref");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"target\": ");
                try self.writeString(d.target);
            },
            .metatype_binding => |*mb| {
                try self.writeString("metatype_binding");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"metatype\": ");
                try self.writeString(mb.metatype);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"binding\": ");
                try self.writeString(mb.binding);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"source_event\": ");
                try self.writeString(mb.source_event);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"dest_event\": ");
                if (mb.dest_event) |dest| {
                    try self.writeString(dest);
                } else {
                    try self.write("null");
                }
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"branch\": ");
                try self.writeString(mb.branch);
            },
            .inline_code => |code| {
                try self.writeString("inline_code");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"code\": ");
                try self.writeString(code);
            },
            .foreach => |*fe| {
                try self.writeString("foreach");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"iterable\": ");
                try self.writeString(fe.iterable);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"element_type\": ");
                if (fe.element_type) |et| {
                    try self.writeString(et);
                } else {
                    try self.write("null");
                }
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"branches\": [\n");
                self.indent();
                for (fe.branches, 0..) |*branch, i| {
                    if (i > 0) try self.write(",\n");
                    try self.serializeNamedBranchJson(branch);
                }
                try self.write("\n");
                self.dedent();
                try self.writeIndent();
                try self.write("]");
            },
            .conditional => |*cond| {
                try self.writeString("conditional");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"condition\": ");
                try self.writeString(cond.condition);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"branches\": [\n");
                self.indent();
                for (cond.branches, 0..) |*branch, i| {
                    if (i > 0) try self.write(",\n");
                    try self.serializeNamedBranchJson(branch);
                }
                try self.write("\n");
                self.dedent();
                try self.writeIndent();
                try self.write("]");
            },
            .capture => |*cap| {
                try self.writeString("capture");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"init_expr\": ");
                try self.writeString(cap.init_expr);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"branches\": [\n");
                self.indent();
                for (cap.branches, 0..) |*branch, i| {
                    if (i > 0) try self.write(",\n");
                    try self.serializeNamedBranchJson(branch);
                }
                try self.write("\n");
                self.dedent();
                try self.writeIndent();
                try self.write("]");
            },
            .assignment => |*asgn| {
                try self.writeString("assignment");
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"target\": ");
                try self.writeString(asgn.target);
                try self.write(",\n");
                try self.writeIndent();
                try self.write("\"fields\": [\n");
                self.indent();
                for (asgn.fields, 0..) |*field, i| {
                    if (i > 0) try self.write(",\n");
                    try self.writeIndent();
                    try self.write("{\"name\": ");
                    try self.writeString(field.name);
                    try self.write(", \"value\": ");
                    if (field.expression_str) |expr| {
                        try self.writeString(expr);
                    } else {
                        try self.writeString(field.type);
                    }
                    try self.write("}");
                }
                try self.write("\n");
                self.dedent();
                try self.writeIndent();
                try self.write("]");
            },
        }

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeImportDeclJson(self: *AstSerializer, import: *const ast.ImportDecl) !void {
        try self.writeIndent();
        try self.write("\"path\": ");
        try self.writeString(import.path);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&import.location);
    }

    fn serializeModuleDeclJson(self: *AstSerializer, module: *const ast.ModuleDecl) !void {
        try self.writeIndent();
        try self.write("\"logical_name\": ");
        try self.writeString(module.logical_name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"canonical_path\": ");
        try self.writeString(module.canonical_path);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"is_system\": ");
        try self.write(if (module.is_system) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"annotations\": [\n");
        self.indent();
        for (module.annotations, 0..) |ann, i| {
            if (i > 0) {
                try self.write(",\n");
            }
            try self.writeIndent();
            try self.writeString(ann);
        }
        if (module.annotations.len > 0) {
            try self.write("\n");
        }
        self.dedent();
        try self.writeIndent();
        try self.write("]");
    }

    fn serializeHostLineJson(self: *AstSerializer, line: *const ast.HostLine) !void {
        try self.writeIndent();
        try self.write("\"module\": ");
        try self.writeString(line.module);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&line.location);
    }

    fn serializeParseErrorNodeJson(self: *AstSerializer, error_node: *const ast.ParseErrorNode) !void {
        try self.writeIndent();
        try self.write("\"code\": ");
        try self.writeString(@tagName(error_node.error_code));
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"message\": ");
        try self.writeString(error_node.message);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&error_node.location);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"raw_text\": ");
        try self.writeString(error_node.raw_text);

        if (error_node.hint) |hint| {
            try self.write(",\n");
            try self.writeIndent();
            try self.write("\"hint\": ");
            try self.writeString(hint);
        }
    }

    fn serializeEventTapJson(self: *AstSerializer, tap: *const ast.EventTap) !void {
        try self.writeIndent();
        try self.write("\"source\": ");
        if (tap.source) |*src| {
            try self.serializeDottedPathJson(src);
        } else {
            try self.writeString("*");
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"destination\": ");
        if (tap.destination) |*dest| {
            try self.serializeDottedPathJson(dest);
        } else {
            try self.writeString("*");
        }
        try self.write(",\n");

        // Continuations - THE KEY THING WE'RE TESTING!
        try self.writeIndent();
        try self.write("\"continuations\": [\n");
        self.indent();
        for (tap.continuations, 0..) |*cont, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeContinuationJson(cont);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("],\n");

        try self.writeIndent();
        try self.write("\"is_input_tap\": ");
        try self.write(if (tap.is_input_tap) "true" else "false");
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&tap.location);
    }

    fn serializeLabelDeclJson(self: *AstSerializer, label: *const ast.LabelDecl) !void {
        try self.writeIndent();
        try self.write("\"name\": ");
        try self.writeString(label.name);
    }

    fn serializeSubflowImplJson(self: *AstSerializer, subflow: *const ast.SubflowImpl) !void {
        try self.writeIndent();
        try self.write("\"event_path\": ");
        try self.serializeDottedPathJson(&subflow.event_path);
        try self.write(",\n");

        // Serialize body (flow or immediate branch constructor)
        try self.writeIndent();
        try self.write("\"body\": ");
        switch (subflow.body) {
            .flow => |flow| {
                try self.write("{\n");
                self.indent();
                try self.writeIndent();
                try self.write("\"type\": \"flow\",\n");
                try self.writeIndent();
                try self.write("\"flow\": {\n");
                self.indent();
                try self.serializeFlowJson(&flow);
                self.dedent();
                try self.writeIndent();
                try self.write("}\n");
                self.dedent();
                try self.writeIndent();
                try self.write("}");
            },
            .immediate => |imm| {
                try self.write("{\n");
                self.indent();
                try self.writeIndent();
                try self.write("\"type\": \"immediate\",\n");
                try self.writeIndent();
                try self.write("\"immediate\": ");
                try self.serializeBranchConstructorJson(&imm);
                try self.write("\n");
                self.dedent();
                try self.writeIndent();
                try self.write("}");
            },
        }
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&subflow.location);
    }

    fn serializeHostTypeDeclJson(self: *AstSerializer, host_type: *const ast.HostTypeDecl) !void {
        try self.writeIndent();
        try self.write("\"name\": ");
        try self.writeString(host_type.name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"shape\": ");
        try self.serializeShapeJson(&host_type.shape);
    }

    fn serializeDottedPathJson(self: *AstSerializer, path: *const ast.DottedPath) !void {
        try self.write("[");
        for (path.segments, 0..) |segment, i| {
            if (i > 0) try self.write(", ");
            try self.writeString(segment);
        }
        try self.write("]");
    }

    fn serializeShapeJson(self: *AstSerializer, shape: *const ast.Shape) !void {
        try self.write("{\n");
        self.indent();

        // Output fields array with full field information
        try self.writeIndent();
        try self.write("\"fields\": [\n");
        self.indent();

        for (shape.fields, 0..) |*field, i| {
            if (i > 0) try self.write(",\n");
            try self.writeIndent();
            try self.write("{\n");
            self.indent();

            // Field name
            try self.writeIndent();
            try self.write("\"name\": ");
            try self.writeString(field.name);
            try self.write(",\n");

            // Field type
            try self.writeIndent();
            try self.write("\"type\": ");
            if (field.module_path) |module_path| {
                // Output as "module.path:Type" for cross-module types
                const full_type = try std.fmt.allocPrint(self.allocator, "{s}:{s}", .{module_path, field.type});
                defer self.allocator.free(full_type);
                try self.writeString(full_type);
            } else {
                try self.writeString(field.type);
            }
            try self.write(",\n");

            // Special type flags
            try self.writeIndent();
            try self.write("\"is_source\": ");
            try self.write(if (field.is_source) "true" else "false");
            try self.write(",\n");

            try self.writeIndent();
            try self.write("\"is_file\": ");
            try self.write(if (field.is_file) "true" else "false");
            try self.write(",\n");

            try self.writeIndent();
            try self.write("\"is_embed_file\": ");
            try self.write(if (field.is_embed_file) "true" else "false");

            try self.write("\n");
            self.dedent();
            try self.writeIndent();
            try self.write("}");
        }

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("]\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeBranchJson(self: *AstSerializer, branch: *const ast.Branch) !void {
        try self.writeIndent();
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"name\": ");
        try self.writeString(branch.name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"payload\": ");
        try self.serializeShapeJson(&branch.payload);

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeBranchConstructorJson(self: *AstSerializer, bc: *const ast.BranchConstructor) !void {
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"branch_name\": ");
        try self.writeString(bc.branch_name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"fields\": [\n");
        self.indent();
        for (bc.fields, 0..) |*field, i| {
            if (i > 0) try self.write(",\n");
            try self.writeIndent();
            try self.write("{\n");
            self.indent();

            try self.writeIndent();
            try self.write("\"name\": ");
            try self.writeString(field.name);
            try self.write(",\n");

            try self.writeIndent();
            try self.write("\"type\": ");
            try self.writeString(field.type);
            try self.write(",\n");

            try self.writeIndent();
            try self.write("\"expression_str\": ");
            if (field.expression_str) |expr| {
                try self.writeString(expr);
            } else {
                try self.write("null");
            }

            try self.write("\n");
            self.dedent();
            try self.writeIndent();
            try self.write("}");
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("],\n");

        try self.writeIndent();
        try self.write("\"has_expressions\": ");
        try self.write(if (bc.has_expressions) "true" else "false");

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeLocationJson(self: *AstSerializer, location: anytype) !void {
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"file\": ");
        try self.writeString(location.file);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"line\": ");
        const line_str = try std.fmt.allocPrint(self.allocator, "{d}", .{location.line});
        defer self.allocator.free(line_str);
        try self.write(line_str);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"col\": ");
        const col_str = try std.fmt.allocPrint(self.allocator, "{d}", .{location.column});
        defer self.allocator.free(col_str);
        try self.write(col_str);

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeSourceJson(self: *AstSerializer, source: *const ast.Source) !void {
        try self.write("{\n");
        self.indent();

        // Text
        try self.writeIndent();
        try self.write("\"text\": ");
        try self.writeString(source.text);
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&source.location);
        try self.write(",\n");

        // Scope
        try self.writeIndent();
        try self.write("\"scope\": ");
        try self.serializeCapturedScopeJson(&source.scope);
        try self.write(",\n");

        // Phantom type
        try self.writeIndent();
        try self.write("\"phantom_type\": ");
        if (source.phantom_type) |pt| {
            try self.writeString(pt);
        } else {
            try self.write("null");
        }

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeCapturedExpressionJson(self: *AstSerializer, expr: *const ast.CapturedExpression) !void {
        try self.write("{\n");
        self.indent();

        // Text
        try self.writeIndent();
        try self.write("\"text\": ");
        try self.writeString(expr.text);
        try self.write(",\n");

        // Location
        try self.writeIndent();
        try self.write("\"location\": ");
        try self.serializeLocationJson(&expr.location);
        try self.write(",\n");

        // Scope
        try self.writeIndent();
        try self.write("\"scope\": ");
        try self.serializeCapturedScopeJson(&expr.scope);

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeCapturedScopeJson(self: *AstSerializer, scope: *const ast.CapturedScope) !void {
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"bindings\": [\n");
        self.indent();
        for (scope.bindings, 0..) |*binding, i| {
            if (i > 0) try self.write(",\n");
            try self.serializeScopeBindingJson(binding);
        }
        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("]\n");

        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }

    fn serializeScopeBindingJson(self: *AstSerializer, binding: *const ast.ScopeBinding) !void {
        try self.writeIndent();
        try self.write("{\n");
        self.indent();

        try self.writeIndent();
        try self.write("\"name\": ");
        try self.writeString(binding.name);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"type\": ");
        try self.writeString(binding.type);
        try self.write(",\n");

        try self.writeIndent();
        try self.write("\"value_ref\": ");
        try self.writeString(binding.value_ref);

        try self.write("\n");
        self.dedent();
        try self.writeIndent();
        try self.write("}");
    }
};

// Tests for AST Serializer

test "serialize simple Koru program" {
    const allocator = std.testing.allocator;
    
    const source =
        \\const std = @import("std");
        \\
        \\~event hello {}
        \\| done {}
        \\
        \\const x = 42;
        \\
        \\~proc hello {
        \\    std.debug.print("Hello!\n", .{});
        \\    return .{ .done = .{} };
        \\}
    ;
    
    // Parse the source
    var parser = try Parser.init(allocator, source, "test.kz");
    defer parser.deinit();
    
    var parse_result = try parser.parse();
    defer parse_result.deinit();
    
    // Serialize the AST
    var serializer = try AstSerializer.init(allocator);
    defer serializer.deinit();
    
    const serialized = try serializer.serialize(&parse_result.source_file);
    defer allocator.free(serialized);
    
    // Verify the output contains expected elements
    try std.testing.expect(std.mem.indexOf(u8, serialized, "PROGRAM_AST") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".host_line = \"const std = @import(\\\"std\\\");\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".event_decl = EventDecl{") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".proc_decl = ProcDecl{") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".host_line = \"const x = 42;\"") != null);
    
    // Print a sample for visual inspection
    std.debug.print("\n=== Sample of serialized AST ===\n", .{});
    const sample_end = @min(serialized.len, 1000);
    std.debug.print("{s}\n", .{serialized[0..sample_end]});
}

test "serialize Zig lines are preserved" {
    const allocator = std.testing.allocator;
    
    const source =
        \\fn helper(x: i32) i32 {
        \\    return x * 2;
        \\}
        \\
        \\const data = [_]u8{1, 2, 3};
    ;
    
    var parser = try Parser.init(allocator, source, "test.kz");
    defer parser.deinit();
    
    var parse_result = try parser.parse();
    defer parse_result.deinit();
    
    var serializer = try AstSerializer.init(allocator);
    defer serializer.deinit();
    
    const serialized = try serializer.serialize(&parse_result.source_file);
    defer allocator.free(serialized);
    
    // Check that Zig lines are preserved
    try std.testing.expect(std.mem.indexOf(u8, serialized, "fn helper(x: i32) i32 {") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, "return x * 2;") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, "const data = [_]u8{1, 2, 3};") != null);
}

test "serialize proc body preserves Zig code" {
    const allocator = std.testing.allocator;
    
    const source =
        \\~event compute { x: i32 }
        \\| result { value: i32 }
        \\
        \\~proc compute {
        \\    const doubled = e.x * 2;
        \\    const tripled = e.x * 3;
        \\    return .{ .result = .{ .value = doubled + tripled } };
        \\}
    ;
    
    var parser = try Parser.init(allocator, source, "test.kz");
    defer parser.deinit();
    
    var parse_result = try parser.parse();
    defer parse_result.deinit();
    
    var serializer = try AstSerializer.init(allocator);
    defer serializer.deinit();
    
    const serialized = try serializer.serialize(&parse_result.source_file);
    defer allocator.free(serialized);
    
    // Check that proc body is preserved
    try std.testing.expect(std.mem.indexOf(u8, serialized, "const doubled = e.x * 2;") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, "const tripled = e.x * 3;") != null);
}

test "serialize complete mixed program" {
    const allocator = std.testing.allocator;
    
    const source =
        \\// Top-level comment
        \\const std = @import("std");
        \\
        \\pub fn utility() void {
        \\    std.debug.print("Utility function\n", .{});
        \\}
        \\
        \\~import math = "lib/math.kz"
        \\
        \\~event process { input: []const u8 }
        \\| success { output: []const u8 }
        \\| failure { error: []const u8 }
        \\
        \\const config = struct {
        \\    debug: bool = true,
        \\};
        \\
        \\~proc process {
        \\    if (config.debug) {
        \\        std.debug.print("Processing: {s}\n", .{e.input});
        \\    }
        \\    return .{ .success = .{ .output = e.input } };
        \\}
        \\
        \\// Entry point flow
        \\~process(input: "test")
        \\| success s |> _
        \\| failure f |> _
    ;
    
    var parser = try Parser.init(allocator, source, "test.kz");
    defer parser.deinit();
    
    var parse_result = try parser.parse();
    defer parse_result.deinit();
    
    var serializer = try AstSerializer.init(allocator);
    defer serializer.deinit();
    
    const serialized = try serializer.serialize(&parse_result.source_file);
    defer allocator.free(serialized);
    
    // Verify all types of content are serialized
    try std.testing.expect(std.mem.indexOf(u8, serialized, "// Top-level comment") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, "pub fn utility() void") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".import_decl") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".event_decl") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".proc_decl") != null);
    try std.testing.expect(std.mem.indexOf(u8, serialized, ".flow") != null);
    
    // Print for inspection
    std.debug.print("\n=== Complete mixed program serialized ===\n", .{});
    const lines = std.mem.splitScalar(u8, serialized, '\n');
    var line_count: usize = 0;
    var iter = lines;
    while (iter.next()) |line| : (line_count += 1) {
        if (line_count >= 30) break;  // Just show first 30 lines
        std.debug.print("{s}\n", .{line});
    }
    std.debug.print("... (truncated, total length: {} bytes)\n", .{serialized.len});
}