//! EmbeddedFs — an `Fs` provider backed by the koru_std bytes baked into the
//! binary (src/stdlib_bundle.zig, generated by scripts/gen-stdlib-bundle.sh).
//! This is what lets the wasm playground resolve `import "std/io"` with no disk:
//! the stdlib lives at the virtual root "/koru_std" inside the bundle.
//!
//! Stateless — the bundle is a comptime constant, so like DiskFs the `ptr` is
//! unused. Paths are already absolute virtual paths (keys in the bundle), so
//! `canonicalize` is identity.

const std = @import("std");
const bundle = @import("stdlib_bundle");
const mr = @import("module_resolver");
const file_types = @import("file_types");

var instance: u8 = 0;

pub fn fs() mr.Fs {
    return .{ .ptr = @ptrCast(&instance), .vtable = &vtable };
}

const vtable = mr.Fs.VTable{
    .exists = existsImpl,
    .isDir = isDirImpl,
    .listKoruFiles = listKoruFilesImpl,
    .readFile = readFileImpl,
    .canonicalize = canonicalizeImpl,
};

fn lookup(path: []const u8) ?[]const u8 {
    for (bundle.files) |e| {
        if (std.mem.eql(u8, e.path, path)) return e.bytes;
    }
    return null;
}

fn existsImpl(_: *anyopaque, path: []const u8) bool {
    return lookup(path) != null;
}

/// A virtual directory exists if any embedded file sits under `path/`.
fn isDirImpl(_: *anyopaque, path: []const u8) bool {
    for (bundle.files) |e| {
        if (e.path.len > path.len and
            std.mem.startsWith(u8, e.path, path) and
            e.path[path.len] == '/') return true;
    }
    return false;
}

/// Koru files whose direct parent is `dir` (no deeper nesting).
fn listKoruFilesImpl(_: *anyopaque, allocator: std.mem.Allocator, dir: []const u8) anyerror![][]const u8 {
    var files = std.ArrayList([]const u8){ .items = &.{}, .capacity = 0 };
    errdefer {
        for (files.items) |f| allocator.free(f);
        files.deinit(allocator);
    }
    for (bundle.files) |e| {
        if (e.path.len <= dir.len) continue;
        if (!std.mem.startsWith(u8, e.path, dir)) continue;
        if (e.path[dir.len] != '/') continue;
        const rest = e.path[dir.len + 1 ..];
        if (std.mem.indexOfScalar(u8, rest, '/') != null) continue; // not a direct child
        if (!file_types.isKoruFile(e.path)) continue;
        try files.append(allocator, try allocator.dupe(u8, e.path));
    }
    return try files.toOwnedSlice(allocator);
}

fn readFileImpl(_: *anyopaque, allocator: std.mem.Allocator, path: []const u8) anyerror!?[]u8 {
    if (lookup(path)) |bytes| return try allocator.dupe(u8, bytes);
    return null;
}

fn canonicalizeImpl(_: *anyopaque, allocator: std.mem.Allocator, path: []const u8) anyerror![]u8 {
    // Bundle keys are already absolute virtual paths; nothing to resolve.
    return try allocator.dupe(u8, path);
}
